import type { Command } from "commander";

export const SUPPORTED_SHELLS = ["bash", "zsh", "fish"] as const;
export type Shell = (typeof SUPPORTED_SHELLS)[number];

export interface CompletionCommand {
  name: string;
  description: string;
  subcommands: CompletionCommand[];
  /** Long option flags declared on this command, e.g. "--cluster". */
  options: string[];
}

/** Collapse a description to a single safe line for a completion script. */
function oneLine(text: string): string {
  return text.replace(/\s+/g, " ").trim();
}

function longFlags(cmd: Command): string[] {
  // Each commander Option's `.long` is the "--flag" form (or null for a short-only flag).
  return cmd.options.flatMap((o) => (o.long ? [o.long] : []));
}

/** Extract the command tree from a live commander `Command` (recurses into subcommands). */
export function commandTree(cmd: Command): CompletionCommand {
  return {
    name: cmd.name(),
    description: oneLine(cmd.description() ?? ""),
    subcommands: cmd.commands.map(commandTree),
    options: longFlags(cmd),
  };
}

/** Top-level command names, sorted. */
function topNames(root: CompletionCommand): string[] {
  return root.subcommands.map((c) => c.name).sort();
}

/** Subcommand names per top-level command that has any (for the second completion word). */
function subcommandMap(root: CompletionCommand): Array<{ command: string; subs: CompletionCommand[] }> {
  return root.subcommands
    .filter((c) => c.subcommands.length > 0)
    .map((c) => ({ command: c.name, subs: c.subcommands }));
}

/** Global flags (the root program's options) plus --help. */
function globalFlags(root: CompletionCommand): string[] {
  return [...new Set([...root.options, "--help"])].sort();
}

function bash(root: CompletionCommand, names: string[]): string {
  const commands = topNames(root).join(" ");
  const globals = globalFlags(root).join(" ");
  const arms = subcommandMap(root)
    .map(
      ({ command, subs }) =>
        `    ${command})\n      if [ "$cword" -eq 2 ]; then COMPREPLY=( $(compgen -W "${subs
          .map((s) => s.name)
          .sort()
          .join(" ")}" -- "$cur") ); return; fi ;;`,
    )
    .join("\n");
  return `# launch-pad bash completion — generated by \`launch-pad completions bash\`
_launch_pad_complete() {
  local cur cword cmd
  cur="\${COMP_WORDS[COMP_CWORD]}"
  cword="$COMP_CWORD"
  local commands="${commands}"
  local globals="${globals}"
  if [ "$cword" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "$commands $globals" -- "$cur") )
    return
  fi
  cmd="\${COMP_WORDS[1]}"
  case "$cmd" in
${arms}
  esac
  COMPREPLY=( $(compgen -W "$globals" -- "$cur") )
}
complete -F _launch_pad_complete ${names.join(" ")}
`;
}

function zshDescribe(items: CompletionCommand[]): string {
  return items
    .map((c) => c.name)
    .sort()
    .map((n) => {
      const item = items.find((c) => c.name === n)!;
      const desc = item.description.replace(/:/g, " ").replace(/'/g, "");
      return `    '${n}:${desc}'`;
    })
    .join("\n");
}

function zsh(root: CompletionCommand, names: string[]): string {
  const arms = subcommandMap(root)
    .map(
      ({ command, subs }) =>
        `    ${command})\n      if (( CURRENT == 3 )); then\n        local -a subs\n        subs=(\n${zshDescribe(
          subs,
        )}\n        )\n        _describe '${command} subcommand' subs\n      fi ;;`,
    )
    .join("\n");
  return `#compdef ${names.join(" ")}
# launch-pad zsh completion — generated by \`launch-pad completions zsh\`
_launch_pad_complete() {
  local -a commands
  commands=(
${zshDescribe(root.subcommands)}
  )
  if (( CURRENT == 2 )); then
    _describe 'launch-pad command' commands
    return
  fi
  case "\${words[2]}" in
${arms}
  esac
}
compdef _launch_pad_complete ${names.join(" ")}
`;
}

function fishDesc(text: string): string {
  return text.replace(/'/g, "").slice(0, 80);
}

function fish(root: CompletionCommand, names: string[]): string {
  const lines: string[] = ["# launch-pad fish completion — generated by `launch-pad completions fish`"];
  for (const name of names) {
    lines.push(`# completions for ${name}`);
    lines.push(`complete -c ${name} -f`);
    for (const c of root.subcommands) {
      lines.push(`complete -c ${name} -n __fish_use_subcommand -a ${c.name} -d '${fishDesc(c.description)}'`);
    }
    for (const { command, subs } of subcommandMap(root)) {
      for (const s of subs) {
        lines.push(
          `complete -c ${name} -n "__fish_seen_subcommand_from ${command}" -a ${s.name} -d '${fishDesc(s.description)}'`,
        );
      }
    }
    for (const flag of globalFlags(root)) {
      lines.push(`complete -c ${name} -l ${flag.replace(/^--/, "")}`);
    }
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Render a shell-completion script for the CLI from its command tree. `names` is the
 * set of binary names to wire (e.g. `["launch-pad", "lpd"]`). Pure.
 */
export function generateCompletion(shell: Shell, root: CompletionCommand, names: string[]): string {
  switch (shell) {
    case "bash":
      return bash(root, names);
    case "zsh":
      return zsh(root, names);
    case "fish":
      return fish(root, names);
  }
}
