/**
 * launch-pad real-AWS regression for **alerting** (`launch-pad alerts check`).
 *
 * Worker-only (no domain). Proves the health probe fires on a REAL fault: a node that
 * was healthy but whose instance dies out-of-band (so the registry still says `ready`
 * while the agent stops heartbeating) is flagged, delivered to a webhook, and exits non-zero.
 *
 * Scenario:
 *   deploy a worker → node is `ready`, agent live      → `alerts check` is clean (exit 0)
 *   terminate the EC2 instance directly (bypass lp)     → registry stays `ready`, heartbeat freezes
 *   wait out the staleness window                       → `alerts check` fires `heartbeat-stale`,
 *                                                          POSTs a local webhook, exits non-zero
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:alerts   (`--keep` skips teardown)
 */
import { randomBytes } from "node:crypto";
import { createServer, type Server } from "node:http";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];
const STALE_MS = 20_000;

interface NodeShow {
  node: { nodeId: string; instanceId: string | null; role: string; state: string };
  status: { services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }> } | null;
}
interface AlertsJson {
  cluster: string;
  checkedNodes: number;
  alertCount: number;
  delivered: boolean;
  alerts: Array<{ nodeId: string; kind: string; severity: string; message: string }>;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(fn: () => Promise<T>, opts: { tries: number; delayMs: number; until: (r: T) => boolean }): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

async function runningCount(cli: Cli, node: string, cluster: string, service: string): Promise<number> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? []).filter((r) => r.state === "running" && r.containerId).length;
}

/** A tiny local webhook receiver — captures the bodies the CLI POSTs. */
function webhookReceiver(): { server: Server; url: Promise<string>; received: unknown[] } {
  const received: unknown[] = [];
  const server = createServer((req, res) => {
    let body = "";
    req.on("data", (c) => (body += c));
    req.on("end", () => {
      try {
        received.push(JSON.parse(body));
      } catch {
        received.push(body);
      }
      res.writeHead(200, { "content-type": "application/json" });
      res.end('{"ok":true}');
    });
  });
  const url = new Promise<string>((resolve) => {
    server.listen(0, "127.0.0.1", () => {
      const addr = server.address();
      const port = typeof addr === "object" && addr ? addr.port : 0;
      resolve(`http://127.0.0.1:${port}`);
    });
  });
  return { server, url, received };
}

function prepareWorkerFixture(project: string, node: string, service: string): string {
  const src = join(repoRoot, "examples", "both-node-web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-alerts-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad alerts e2e — do not edit.
project = "${project}"

[[service]]
name = "${service}"
node = "${node}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS alerts e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:alerts\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-alerts-${runId}`;
  const node = "alerts-both";
  const project = "alerts";
  const service = "worker";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareWorkerFixture(project, node, service);
  const hook = webhookReceiver();
  const webhookUrl = await hook.url;

  note(`run ${runId} · cluster ${cluster} · region ${region} · alerts (worker, fault = terminated instance)`);
  note(`isolated LAUNCHPAD_HOME=${home} · webhook ${webhookUrl}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "alerts e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    hook.server.close();
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    let instanceId = "";
    await step("create a cluster + deploy a worker (node becomes ready)", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", node, "--role", "both", "--cluster", cluster, "--yes"]);
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const count = await retry(() => runningCount(cli, node, cluster, service), { tries: 18, delayMs: 10_000, until: (n) => n === 1 });
      assertEquals(count, 1, "worker is running 1 replica");
      const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
      assert(!!show.node.instanceId, "node has an instance id");
      instanceId = show.node.instanceId!;
    });

    await step("a healthy cluster yields no alerts (exit 0, webhook not called)", async () => {
      const out = await cli.json<AlertsJson>(["alerts", "check", "--cluster", cluster]);
      assertEquals(out.alertCount, 0, "no alerts when healthy");
      assertEquals(out.delivered, false, "webhook not called when there's nothing to alert");
      assertEquals(hook.received.length, 0, "the webhook receiver got nothing");
    });

    await step("terminate the instance out-of-band (registry still thinks it's ready)", async () => {
      await execa("aws", ["ec2", "terminate-instances", "--region", region, "--instance-ids", instanceId]);
      note(`terminated ${instanceId} directly — launch-pad's registry is now stale`);
      // Let the agent stop heartbeating + the last status age past the staleness window.
      await sleep(STALE_MS + 15_000);
    });

    await step("alerts check fires heartbeat-stale, POSTs the webhook, exits non-zero", async () => {
      const res = await retry(
        () => cli.run(["alerts", "check", "--cluster", cluster, "--stale", String(STALE_MS), "--webhook", webhookUrl, "--json"], { allowFail: true }),
        { tries: 12, delayMs: 10_000, until: (r) => r.exitCode !== 0 },
      );
      assert(res.exitCode !== 0, `alerts check exits non-zero on an alert (exit ${res.exitCode})`);
      const out = JSON.parse(res.stdout) as AlertsJson;
      assert(out.alertCount >= 1, `at least one alert (${out.alertCount})`);
      assertEquals(out.alerts[0]!.kind, "heartbeat-stale", "the alert is a stale heartbeat");
      assertEquals(out.alerts[0]!.nodeId, node, "the alert names the dead node");
      assertEquals(out.delivered, true, "the alert was delivered to the webhook");
      assert(hook.received.length >= 1, "the local webhook receiver got the POST");
      const payload = hook.received[hook.received.length - 1] as { text?: string; alertCount?: number };
      assert(typeof payload.text === "string" && /heartbeat is stale|never reported/.test(payload.text), "the webhook body describes the stale heartbeat");
      note(`webhook received: ${payload.text?.split("\n")[0]}`);
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}". Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --yes`);
      hook.server.close();
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
