/**
 * launch-pad real-AWS regression for capacity auto-add — when a cluster-placed deploy
 * doesn't fit the current pool, deploy auto-provisions another app node instead of
 * erroring "reduce cpu/memory/replicas".
 *
 * Worker-only (no domain/cert/DNS) but it builds + deploys (needs Docker). A worker sized
 * at cpu=256/memory=512 fits 2 replicas per t3.small (1536 MB allocatable, memory-bound),
 * so: first deploy at replicas=1 bootstraps one node (app-1), then scaling to replicas=3
 * overflows it and auto-adds a second node (app-2), spreading 2/1.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:auto-add   (`--keep` skips teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Running replica count for a service on one node (0 if the node doesn't exist yet). */
async function runningOn(cli: Cli, node: string, cluster: string, service: string): Promise<number> {
  const res = await cli.run(["node", "show", node, "--cluster", cluster, "--json"], { allowFail: true });
  if (res.exitCode !== 0) return 0;
  const show = JSON.parse(res.stdout) as NodeShow;
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? []).filter((r) => r.state === "running" && r.containerId).length;
}

async function totalRunning(cli: Cli, nodes: string[], cluster: string, service: string): Promise<number> {
  let n = 0;
  for (const node of nodes) n += await runningOn(cli, node, cluster, service);
  return n;
}

/** A cluster-auto-placed worker (omit `node`; `schedule = "even"`), 512 MB so 2 fit per t3.small. */
function prepareFixture(spec: { project: string; service: string }): string {
  const src = join(repoRoot, "examples", "both-node-web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-autoadd-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad auto-add e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
schedule = "even"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 512
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS auto-add e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:auto-add\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-autoadd-${runId}`;
  const project = "autoadd";
  const service = "worker";
  const node1 = "app-1"; // bootstrap node
  const node2 = "app-2"; // auto-added on capacity pressure

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareFixture({ project, service });

  note(`run ${runId} · cluster ${cluster} · region ${region} · capacity auto-add`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "auto-add e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create an isolated cluster", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
    });

    await step("first deploy bootstraps a single node (app-1) at replicas=1", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const show = await cli.json<NodeShow>(["node", "show", node1, "--cluster", cluster]);
      assertEquals(show.node.role, "both", "bootstrap node is co-located (both)");
      const ids = await retry(() => runningOn(cli, node1, cluster, service), {
        tries: 18,
        delayMs: 10_000,
        until: (n) => n === 1,
      });
      assertEquals(ids, 1, "worker runs 1 replica on app-1");
      assertEquals(await runningOn(cli, node2, cluster, service), 0, "app-2 does not exist yet");
    });

    await step("scaling to replicas=3 auto-adds a second node and spreads across both", async () => {
      // app-1 (t3.small, 1536 MB allocatable) fits only 2 replicas of 512 MB + surge, so the
      // 3rd replica forces deploy to auto-provision app-2 instead of erroring on capacity.
      await cli.run(
        ["scale", "replicas", service, "3", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      const show = await cli.json<NodeShow>(["node", "show", node2, "--cluster", cluster]);
      assertEquals(show.node.nodeId, node2, "deploy auto-added the second node app-2");
      assertEquals(show.node.role, "both", "the auto-added node is co-located (both)");
      const total = await retry(() => totalRunning(cli, [node1, node2], cluster, service), {
        tries: 24,
        delayMs: 10_000,
        until: (n) => n === 3,
      });
      assertEquals(total, 3, "all 3 replicas run, spread across app-1 + app-2");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
