/**
 * launchpad real-AWS regression for federated `project` + `component` deploys: several
 * repos sharing one logical project, each owning a component, deploying independently
 * without clobbering each other.
 *
 * Deliberately minimal and FAST (same model as deploy-changed): two **worker** services
 * from two separate fixture "repos" (`auth` + `notes`), co-located on the cluster's
 * single app node — no domain → no Caddy/cert/DNS/secrets.
 *
 * On real infrastructure it asserts:
 *   1. A FULL deploy from the `notes` repo leaves the previously-deployed `auth`
 *      component's container byte-for-byte untouched (different footprint owner →
 *      different replace key — the federation guarantee).
 *   2. `project show <project> --json` aggregates BOTH components from the registry.
 *   3. A third repo reusing a sibling's service name is refused BEFORE building
 *      (cross-component uniqueness — components share one ECR namespace).
 *   4. `destroy` from one component repo removes only that component.
 *   5. `destroy --project <name> --yes` (TOML-less) tears down the remaining
 *      component and the registry.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:components   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface ReplicaInfo {
  containerId: string | null;
  state: string;
  image: string;
}
interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  desired: { services: Array<{ project: string; service: string; image: string }> } | null;
  status: { services: Array<{ service: string; replicas?: ReplicaInfo[] }> } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}
interface ProjectShowJson {
  project: string;
  components?: Array<{ component: string; owner: string; services: Array<{ service: string }> }>;
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Running replica container ids for one service on the app node. */
async function running(cli: Cli, node: string, cluster: string, service: string): Promise<string[]> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? [])
    .filter((r) => r.state === "running" && r.containerId)
    .map((r) => r.containerId as string)
    .sort();
}

async function waitForReplicas(cli: Cli, node: string, cluster: string, service: string, count: number) {
  return retry(() => running(cli, node, cluster, service), {
    tries: 30,
    delayMs: 10_000,
    until: (r) => r.length === count,
  });
}

/** Desired.json footprint owners present on a node (federation's replace keys). */
async function desiredOwners(cli: Cli, node: string, cluster: string): Promise<string[]> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  return [...new Set((show.desired?.services ?? []).map((s) => s.project))].sort();
}

/**
 * One component "repo": the example worker app in its own temp dir with a
 * component-scoped launch-pad.toml (worker only — no domain/healthCheck).
 */
async function prepareComponentFixture(spec: {
  project: string;
  component: string;
  service: string;
}): Promise<string> {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), `launch-pad-fed-${spec.component}-`));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad components e2e — do not edit.
project = "${spec.project}"
component = "${spec.component}"

[[service]]
name = "${spec.service}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production", COMPONENT = "${spec.component}" }
`,
    "utf8",
  );
  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", `fed fixture ${spec.component}`], { cwd: dir });
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS components e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:components\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-fed-${runId}`;
  const edgeNode = "fed-edge";
  const appNode = "fed-app";
  const project = "fed";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dirs: string[] = [];

  note(`run ${runId} · cluster ${cluster} · region ${region} · two component repos, worker-only`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(
        out.warnings.length === 0,
        `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`,
      );
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      for (const dir of dirs) rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    const authDir = await prepareComponentFixture({ project, component: "auth", service: "auth" });
    const notesDir = await prepareComponentFixture({ project, component: "notes", service: "notes" });
    dirs.push(authDir, notesDir);

    await step("create an isolated cluster + edge/app node pair", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", appNode, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
    });

    let authV1Ids: string[] = [];
    await step("deploy component `auth` from its own repo", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: authDir });
      authV1Ids = await waitForReplicas(cli, appNode, cluster, "auth", 1);
      assertEquals(authV1Ids.length, 1, "auth is running 1 replica");
      const owners = await desiredOwners(cli, appNode, cluster);
      assert(owners.includes("fed--auth"), `auth's footprint owner is the derived fed--auth (got: ${owners.join(", ")})`);
    });

    await step("FULL deploy of component `notes` does NOT clobber the co-located `auth`", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: notesDir });
      const notes = await waitForReplicas(cli, appNode, cluster, "notes", 1);
      assertEquals(notes.length, 1, "notes is running 1 replica");

      const auth = await running(cli, appNode, cluster, "auth");
      assertEquals(auth.length, 1, "auth is STILL running after notes' FULL deploy");
      assertEquals(
        auth.join(","),
        authV1Ids.join(","),
        "auth's container was untouched (same id) — sibling components never replace each other",
      );
      const owners = await desiredOwners(cli, appNode, cluster);
      assert(
        owners.includes("fed--auth") && owners.includes("fed--notes"),
        `both component owners coexist in desired.json (got: ${owners.join(", ")})`,
      );
    });

    await step("`project show fed` aggregates both components from the registry", async () => {
      const show = await cli.json<ProjectShowJson>(["project", "show", project, "--cluster", cluster]);
      const components = (show.components ?? []).map((c) => c.component).sort();
      assertEquals(components.join(","), "auth,notes", "project show lists both components");
      const authView = (show.components ?? []).find((c) => c.component === "auth");
      assertEquals(authView?.owner, "fed--auth", "auth's owner is recorded in the registry view");
      assertEquals(authView?.services[0]?.service, "auth", "auth's service is aggregated");
    });

    await step("a sibling component reusing the service name `auth` is refused pre-build", async () => {
      const chatDir = await prepareComponentFixture({ project, component: "chat", service: "auth" });
      dirs.push(chatDir);
      const res = await cli.run(["deploy", "--cluster", cluster, "--yes"], { cwd: chatDir, allowFail: true });
      assert(res.exitCode !== 0, "deploy exited non-zero on the cross-component service-name conflict");
      assert(
        /service name conflict/i.test(res.stderr + res.stdout),
        "the error names the cross-component service conflict",
      );
    });

    await step("`destroy` from the auth repo removes ONLY the auth component", async () => {
      await cli.run(["destroy", "--yes", "--cluster", cluster], { cwd: authDir });
      await retry(() => running(cli, appNode, cluster, "auth"), {
        tries: 30,
        delayMs: 10_000,
        until: (r) => r.length === 0,
      });
      const notes = await running(cli, appNode, cluster, "notes");
      assertEquals(notes.length, 1, "notes survives auth's destroy");
      const owners = await desiredOwners(cli, appNode, cluster);
      assert(!owners.includes("fed--auth"), "fed--auth is gone from desired.json");
      assert(owners.includes("fed--notes"), "fed--notes is still published");
    });

    await step("`destroy --project fed` (TOML-less) tears down the rest + the registry", async () => {
      await cli.run(["destroy", "--project", project, "--yes", "--cluster", cluster]);
      await retry(() => running(cli, appNode, cluster, "notes"), {
        tries: 30,
        delayMs: 10_000,
        until: (r) => r.length === 0,
      });
      const owners = await desiredOwners(cli, appNode, cluster);
      assertEquals(owners.join(","), "", "no footprint owners remain in desired.json");
      const res = await cli.run(["destroy", "--project", project, "--yes", "--cluster", cluster], {
        allowFail: true,
      });
      assert(res.exitCode !== 0, "a second --project destroy finds no registry (it was deleted)");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
