/**
 * launchpad real-AWS regression for **scheduled (cron) services** — a worker with
 * `cron = "* * * * *"` is run ONCE PER FIRE by the agent (a fresh container each
 * minute that exits 0), instead of being kept alive as a long-running replica.
 *
 * What this proves end-to-end on a real node:
 *   deploy converges      → a cron service idles at 0 running replicas, yet deploy
 *                           exits 0 (the convergence watch expects 0 for cron)
 *   first fire runs       → status.json grows a `cron` rollup: lastRunAt set,
 *                           lastExitCode 0, nextRunAt scheduled
 *   second fire runs      → lastRunAt ADVANCES to a later minute (periodic re-fire,
 *                           not a one-shot) and stays exit 0
 *   config lock           → editing the cron expression after the first deploy is
 *                           REFUSED (cadence is locked identity)
 *   destroy               → the job's containers + state leave the node
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:cron   (`--keep` skips teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface CronRollup {
  lastRunAt: string | null;
  lastExitCode: number | null;
  nextRunAt: string | null;
}
interface NodeShow {
  node: { nodeId: string; instanceId: string | null; state: string };
  status: {
    services: Array<{
      service: string;
      state: string;
      message?: string;
      cron?: CronRollup;
      replicas?: Array<{ state: string }>;
    }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}
interface UndeployJson {
  destroyed: boolean;
  baselineCleared: boolean;
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

async function cronStatus(cli: Cli, node: string, cluster: string, service: string): Promise<CronRollup | null> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return svc?.cron ?? null;
}

function writeToml(dir: string, project: string, service: string, cron: string): void {
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad cron e2e — do not edit.
project = "${project}"

[[service]]
name = "${service}"
cron = "${cron}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
`,
    "utf8",
  );
}

function prepareFixture(project: string, service: string): string {
  const src = join(repoRoot, "examples", "cron-task");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-cron-"));
  for (const file of ["Dockerfile", "package.json", "task.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeToml(dir, project, service, "* * * * *");
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS cron-scheduling e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:cron\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-cron-${runId}`;
  const edgeNode = "cron-edge";
  const appNode = "cron-app";
  const project = "cronjob";
  const service = "tick";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareFixture(project, service);

  note(`run ${runId} · cluster ${cluster} · region ${region} · scheduled (cron) worker`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "cron e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(
        out.warnings.length === 0,
        `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`,
      );
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create a cluster + provision the edge + app node pair", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", appNode, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
      const show = await cli.json<NodeShow>(["node", "show", appNode, "--cluster", cluster]);
      assert(!!show.node.instanceId, "app node has an EC2 instance id");
    });

    await step("deploy the cron service — converges with ZERO long-running replicas", async () => {
      const res = await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], {
        cwd: dir,
        allowFail: true,
      });
      assert(res.exitCode === 0, `deploy exited 0 for a service that never keeps a replica running\n${res.stderr}`);
    });

    let firstRun = "";
    await step("the first fire runs within ~2 minutes and exits 0", async () => {
      const cron = await retry(() => cronStatus(cli, appNode, cluster, service), {
        tries: 24,
        delayMs: 10_000,
        until: (c) => c?.lastRunAt != null && c.lastExitCode === 0,
      });
      assert(cron?.lastRunAt != null, `a run was recorded (lastRunAt ${cron?.lastRunAt})`);
      assertEquals(cron?.lastExitCode, 0, "the run exited 0");
      assert(cron?.nextRunAt != null, `the next fire is scheduled (${cron?.nextRunAt})`);
      firstRun = cron?.lastRunAt ?? "";
      note(`first run at ${firstRun}`);
    });

    await step("a SECOND fire runs on the next minute (periodic, not one-shot)", async () => {
      const cron = await retry(() => cronStatus(cli, appNode, cluster, service), {
        tries: 24,
        delayMs: 10_000,
        until: (c) => c?.lastRunAt != null && c.lastRunAt > firstRun && c.lastExitCode === 0,
      });
      assert(
        cron?.lastRunAt != null && cron.lastRunAt > firstRun,
        `lastRunAt advanced (${firstRun} → ${cron?.lastRunAt})`,
      );
      assertEquals(cron?.lastExitCode, 0, "the second run also exited 0");
      note(`second run at ${cron?.lastRunAt}`);
    });

    await step("config lock REFUSES changing the cron expression after the first deploy", async () => {
      writeToml(dir, project, service, "*/2 * * * *"); // cadence is locked identity
      await execa("git", [...GIT_ID, "commit", "-aqm", "change cadence"], { cwd: dir });
      const res = await cli.run(["deploy", "--service", service, "--cluster", cluster, "--yes"], {
        cwd: dir,
        allowFail: true,
      });
      assert(res.exitCode !== 0, "deploy is rejected when the cron expression changes");
      assert(
        /not allowed after the initial deploy|locked fields changed|only cpu, memory/.test(res.stderr + res.stdout),
        "the rejection is a config-lock violation",
      );
      writeToml(dir, project, service, "* * * * *"); // restore so teardown is clean
    });

    await step("destroy removes the scheduled job from the node", async () => {
      const out = await cli.json<UndeployJson>(
        ["destroy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      assert(out.destroyed, "destroy reported success");
      const cron = await retry(() => cronStatus(cli, appNode, cluster, service), {
        tries: 12,
        delayMs: 10_000,
        until: (c) => c === null,
      });
      assertEquals(cron, null, "the cron service no longer reports on the node");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
