/**
 * launchpad real-AWS regression for `deploy --changed <ref>` (monorepo "deploy only
 * what changed") AND the partial-deploy correctness it depends on: a SUBSET deploy must
 * PRESERVE a project's co-located siblings on a shared node — it upserts each node's
 * desired.json instead of replacing the whole footprint. (Before the fix, publishing one
 * service's desired state silently dropped the project's other co-located services, and
 * the agent tore down their containers on the next poll.)
 *
 * Deliberately minimal and FAST: two co-located **worker** services (`api` + `worker`) in
 * separate build contexts sharing the cluster's single app node — no domain → no
 * Caddy/cert/DNS/secrets, so it's free of the Let's-Encrypt/SSM dependencies the full
 * lifecycle e2e needs.
 *
 * On real infrastructure it asserts:
 *   1. A partial deploy through the EXISTING `scale` path (`--service worker`) rolls
 *      `worker` and leaves the co-located `api` container byte-for-byte untouched — the
 *      bug fix; before it, the merge dropped `api` entirely.
 *   2. `deploy --changed <v1>` after a content change to ONLY apps/worker selects just
 *      `worker`, rolls it to a new image, and leaves `api` (published image + container)
 *      untouched.
 *   3. `deploy --changed HEAD` with nothing changed is a clean no-op (exit 0, nothing rolls).
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:deploy-changed   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface ReplicaInfo {
  containerId: string | null;
  state: string;
  image: string;
}
interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  desired: { services: Array<{ service: string; image: string }> } | null;
  status: { services: Array<{ service: string; replicas?: ReplicaInfo[] }> } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}
/** Shape of `deploy --json` for both the converged path and the --changed no-op. */
interface DeployJson {
  services?: Array<{ service: string }>;
  reason?: string;
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Running replicas (sorted container ids + the converged image) for one service. */
async function running(
  cli: Cli,
  node: string,
  cluster: string,
  service: string,
): Promise<{ ids: string[]; image: string | null; published: string | null }> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  const live = (svc?.replicas ?? []).filter((r) => r.state === "running" && r.containerId);
  const published = (show.desired?.services ?? []).find((s) => s.service === service)?.image ?? null;
  return {
    ids: live.map((r) => r.containerId as string).sort(),
    image: live[0]?.image ?? null,
    published,
  };
}

/** Wait until the node reports exactly `count` running replicas for the service. */
async function waitForReplicas(cli: Cli, node: string, cluster: string, service: string, count: number) {
  return retry(() => running(cli, node, cluster, service), {
    tries: 30,
    delayMs: 10_000,
    until: (r) => r.ids.length === count,
  });
}

const SERVICES = ["api", "worker"] as const;

/**
 * A throwaway monorepo: the example worker app copied into two independent build
 * contexts (apps/api, apps/worker), each its own service — with a single app node in
 * the cluster, the scheduler co-locates both.
 */
function prepareMonorepoFixture(spec: { project: string }): string {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-changed-"));
  for (const service of SERVICES) {
    const appDir = join(dir, "apps", service);
    mkdirSync(appDir, { recursive: true });
    for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
      copyFileSync(join(src, file), join(appDir, file));
    }
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad deploy --changed e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "api"
dockerfile = "./apps/api/Dockerfile"
context = "./apps/api"
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }

[[service]]
name = "worker"
dockerfile = "./apps/worker/Dockerfile"
context = "./apps/worker"
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function git(dir: string, args: string[]): Promise<string> {
  const { stdout } = await execa("git", [...GIT_ID, ...args], { cwd: dir });
  return stdout.trim();
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS deploy --changed e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:deploy-changed\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-changed-${runId}`;
  const edgeNode = "changed-edge";
  const appNode = "changed-app";
  const project = "changed";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareMonorepoFixture({ project });

  note(`run ${runId} · cluster ${cluster} · region ${region} · monorepo worker-only (no DNS/cert/secret)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  // A clean git repo so the content-addressed image tag is a stable sha.
  await execa("git", ["init", "-q"], { cwd: dir });
  await git(dir, ["add", "-A"]);
  await git(dir, ["commit", "-q", "-m", "deploy --changed e2e fixture (v1)"]);
  const v1Sha = await git(dir, ["rev-parse", "HEAD"]);

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(
        out.warnings.length === 0,
        `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`,
      );
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create an isolated cluster", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
    });

    await step("provision the edge + app node pair", async () => {
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", appNode, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
      const show = await cli.json<NodeShow>(["node", "show", appNode, "--cluster", cluster]);
      assertEquals(show.node.role, "app", "app node role is `app`");
    });

    let apiV1Ids: string[] = [];
    await step("deploy BOTH services (api + worker) co-located on one node", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const api = await waitForReplicas(cli, appNode, cluster, "api", 1);
      const worker = await waitForReplicas(cli, appNode, cluster, "worker", 1);
      assertEquals(api.ids.length, 1, "api is running 1 replica after the first deploy");
      assertEquals(worker.ids.length, 1, "worker is running 1 replica after the first deploy");
      apiV1Ids = api.ids;
    });

    await step(
      "PARTIAL deploy via `scale worker` preserves the co-located `api` (the bug fix)",
      async () => {
        // `scale` runs a `--service worker` deploy. Before the fix, publishing only
        // worker's desired state dropped `api` from this shared node — the agent would
        // then stop+remove the api container. The fix upserts, so `api` survives untouched.
        await cli.run(
          ["scale", "replicas", "worker", "2", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
          { cwd: dir },
        );
        const worker = await waitForReplicas(cli, appNode, cluster, "worker", 2);
        assertEquals(worker.ids.length, 2, "worker converged to 2 replicas after the partial deploy");

        const api = await running(cli, appNode, cluster, "api");
        assertEquals(api.ids.length, 1, "api is STILL running (the partial deploy did not drop it)");
        assertEquals(
          api.ids.join(","),
          apiV1Ids.join(","),
          "api's container was untouched (same id) — the partial deploy did not roll the sibling",
        );
        // Persist the worker-replicas edit so the next git diff/image tag stays clean.
        await git(dir, ["commit", "-qam", "scale worker to 2"]);
      },
    );

    await step(
      "`deploy --changed <v1>` after editing ONLY apps/worker selects + rolls just `worker`",
      async () => {
        const apiBefore = await running(cli, appNode, cluster, "api");
        const workerBefore = await running(cli, appNode, cluster, "worker");

        // Change ONLY the worker context, commit it → its image content (and tag) changes.
        const workerServer = join(dir, "apps", "worker", "server.js");
        writeFileSync(
          workerServer,
          `${readFileSync(workerServer, "utf8")}\n// e2e change ${runId} — worker only\n`,
          "utf8",
        );
        await git(dir, ["commit", "-qam", "edit worker only (v2)"]);

        const out = await cli.json<DeployJson>(
          ["deploy", "--changed", v1Sha, "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
          { cwd: dir },
        );
        const selected = (out.services ?? []).map((s) => s.service).sort();
        assertEquals(selected.join(","), "worker", "deploy --changed selected ONLY the changed service (worker)");

        const worker = await retry(() => running(cli, appNode, cluster, "worker"), {
          tries: 30,
          delayMs: 10_000,
          until: (r) => r.ids.length === 2 && r.ids.join(",") !== workerBefore.ids.join(","),
        });
        assert(
          worker.ids.length === 2 && worker.ids.join(",") !== workerBefore.ids.join(","),
          "worker rolled to new container ids (rebuilt from the changed context)",
        );

        const api = await running(cli, appNode, cluster, "api");
        assertEquals(api.ids.join(","), apiBefore.ids.join(","), "api's container was NOT rolled by the --changed deploy");
        assertEquals(
          api.published,
          apiBefore.published,
          "api keeps its previously-published image — only the changed service was rebuilt",
        );
        assert(
          worker.published !== null && worker.published !== workerBefore.published,
          "worker's published image advanced to the rebuilt tag",
        );
      },
    );

    await softStep("`deploy --changed HEAD` with no changes is a clean no-op (exit 0, nothing rolls)", async () => {
      const apiBefore = await running(cli, appNode, cluster, "api");
      const workerBefore = await running(cli, appNode, cluster, "worker");
      const out = await cli.json<DeployJson>(
        ["deploy", "--changed", "HEAD", "--cluster", cluster, "--yes"],
        { cwd: dir },
      );
      assertEquals((out.services ?? []).length, 0, "no services were selected (nothing changed since HEAD)");
      assert(/no changed services/i.test(out.reason ?? ""), "reported a no-op reason");
      // Give any (erroneous) reconcile a beat, then confirm nothing rolled.
      await sleep(15_000);
      const api = await running(cli, appNode, cluster, "api");
      const worker = await running(cli, appNode, cluster, "worker");
      assertEquals(api.ids.join(","), apiBefore.ids.join(","), "api containers unchanged after the no-op");
      assertEquals(worker.ids.join(","), workerBefore.ids.join(","), "worker containers unchanged after the no-op");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
