/**
 * launch-pad real-AWS regression for `deploy --service <name> --image <uri>` — redeploying
 * an existing immutable ECR tag without rebuilding (the rollback / promote primitive).
 *
 * Worker-only (no domain → no Caddy/cert/DNS, no secrets), so it's fast and agent-agnostic.
 *
 * Scenario:
 *   deploy worker (v1)                         → capture image v1
 *   change content, deploy (v2)                → new image v2, container rolls
 *   deploy --service worker --image <v1>       → rolls back to v1 WITHOUT building
 *   deploy --service worker --image <v1> again → idempotent no-op (same image)
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:deploy-image   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { appendFileSync, copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];

interface DeployJson {
  converged: boolean;
  services: Array<{ service: string; image: string; ok: boolean }>;
}
interface NodeShow {
  status: {
    services: Array<{ service: string; image: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** The image + running container ids the node reports for one service. */
async function observe(cli: Cli, node: string, cluster: string, service: string): Promise<{ image: string | null; ids: string[] }> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  const ids = (svc?.replicas ?? [])
    .filter((r) => r.state === "running" && r.containerId)
    .map((r) => r.containerId as string)
    .sort();
  return { image: svc?.image ?? null, ids };
}

/** Wait until the node reports the service running exactly `image` with 1 replica; return the container id. */
async function waitForImage(cli: Cli, node: string, cluster: string, service: string, image: string): Promise<string> {
  const r = await retry(() => observe(cli, node, cluster, service), {
    tries: 24,
    delayMs: 10_000,
    until: (o) => o.image === image && o.ids.length === 1,
  });
  assertEquals(r.image, image, `node reports ${service} running image ${image.split(":").pop()}`);
  return r.ids[0]!;
}

function prepareFixture(project: string, node: string): string {
  const src = join(repoRoot, "examples", "both-node-web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-deploy-image-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad deploy --image e2e — do not edit.
project = "${project}"

[[service]]
name = "worker"
node = "${node}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

/** Image URI the deploy published for the service. */
function imageOf(deploy: DeployJson, service: string): string {
  const svc = deploy.services.find((s) => s.service === service);
  assert(!!svc?.image, `deploy reported an image for ${service}`);
  return svc!.image;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS deploy --image e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:deploy-image\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-img-${runId}`;
  const node = "img-both";
  const project = "img";
  const service = "worker";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareFixture(project, node);

  note(`run ${runId} · cluster ${cluster} · region ${region} · worker-only (no DNS/cert/secret)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  const commit = async (msg: string): Promise<void> => {
    await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
    await execa("git", [...GIT_ID, "commit", "-q", "-m", msg], { cwd: dir });
  };
  await execa("git", ["init", "-q"], { cwd: dir });
  await commit("deploy-image e2e fixture (v1)");

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {});
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  let v1 = "";
  let v2 = "";
  let idV2 = "";
  try {
    await step("create cluster + provision a both node", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", node, "--role", "both", "--cluster", cluster, "--yes"]);
    });

    await step("deploy the worker (v1) and capture its image", async () => {
      const out = await cli.json<DeployJson>(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      assert(out.converged, "v1 deploy converged");
      v1 = imageOf(out, service);
      note(`v1 image: ${v1}`);
      await waitForImage(cli, node, cluster, service, v1);
    });

    await step("change content + deploy (v2) — a new immutable image is built", async () => {
      appendFileSync(join(dir, "server.js"), `\n// rev 2 — ${runId}\n`);
      await commit("change worker content (v2)");
      const out = await cli.json<DeployJson>(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      assert(out.converged, "v2 deploy converged");
      v2 = imageOf(out, service);
      assert(v2 !== v1, `v2 image differs from v1 (${v2.split(":").pop()} ≠ ${v1.split(":").pop()})`);
      idV2 = await waitForImage(cli, node, cluster, service, v2);
    });

    await step("deploy --image <v1> rolls back to v1 WITHOUT rebuilding", async () => {
      const res = await cli.run(
        ["deploy", "--service", service, "--image", v1, "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      assert(!/building .* linux\/amd64/i.test(res.stderr), "no image was built (--image skips the build)");
      const idV1 = await waitForImage(cli, node, cluster, service, v1);
      assert(idV1 !== idV2, "the container rolled to a new id on rollback");
    });

    await softStep("deploy --image <v1> again is an idempotent no-op", async () => {
      const before = (await observe(cli, node, cluster, service)).ids;
      await cli.run(
        ["deploy", "--service", service, "--image", v1, "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      // Same image already running → the agent shouldn't churn the container.
      const after = await retry(() => observe(cli, node, cluster, service), {
        tries: 6,
        delayMs: 5_000,
        until: (o) => o.image === v1 && o.ids.length === 1,
      });
      assertEquals(after.image, v1, "still on v1 after the repeat rollback");
      assertEquals(after.ids.join(","), before.join(","), "no container churn on the repeat (idempotent)");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    process.exitCode = ran ? (printSummary() ? 0 : 1) : 0;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
