/**
 * launchpad real-AWS regression for named environments — the full PR lifecycle:
 *
 *   deploy --env pr-a --ttl 1m         → env footprint + marker (zero DNS writes)
 *   deploy --env pr-b                  → second env, no TTL (never expires)
 *   destroy --list-envs                → both enumerated, with expiry metadata
 *   destroy --prune-expired --yes      → destroys ONLY the expired env: containers stopped,
 *                                        its projects/ state swept; the TTL-less env is
 *                                        untouched
 *   destroy --env pr-b --yes           → explicit teardown of the survivor
 *   destroy --prune-expired --yes      → clean no-op
 *
 * One edge + one app node, one auto-placed web service fronted by the edge. DNS is
 * user-managed (a wildcard at the edge covers every env subdomain), so this e2e needs
 * NO hosted zone and never writes DNS — it asserts the marker lifecycle and that the
 * deploy surfaces the projected domains. HTTPS/cert issuance is deliberately out of
 * scope — `run.ts` owns that path.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:destroy-env
 * (`--keep` / LAUNCHPAD_E2E_KEEP=1 skips teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

interface NodeShow {
  node: { nodeId: string; role: string; publicIp: string | null; state: string };
  status: { services: Array<{ project: string; service: string; state: string; runningReplicas: number }> } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}
interface DeployJson {
  converged?: boolean;
  dns?: Array<{ domain: string; eip: string | null }>;
}
interface EnvListJson {
  envs: Array<{
    project: string;
    env: string;
    owner: string;
    expiresAt: string | null;
    expired: boolean;
    domains: string[];
  }>;
}
interface PrunePassJson {
  pruned: Array<{ owner: string; nodes: string[]; sweptObjects: number }>;
  kept: string[];
  failed?: Array<{ owner: string; error: string }>;
}
interface EnvDestroyJson {
  destroyed: boolean;
  owner: string;
  nodes: string[];
}

/** The example app + a single auto-placed web service (fronted by the cluster edge). */
async function prepareEnvFixture(spec: {
  project: string;
  service: string;
  domain: string;
}): Promise<string> {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-destroy-env-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad destroy-env e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
domain = "${spec.domain}"
port = 3000
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1

[service.healthCheck]
path = "/healthz"
`,
    "utf8",
  );
  const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];
  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "destroy-env e2e fixture"], { cwd: dir });
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS destroy-env e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:destroy-env\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const baseDomain = process.env.LAUNCHPAD_E2E_DOMAIN ?? "e2e-test.launch-pad.agentsystem.dev";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-prev-${runId}`;
  const edgeNode = "prev-edge";
  const appNode = "prev-app";
  const project = "prev";
  const service = "web";
  // The TOML's literal domain; deploy --env projects it to `prev-<id>-<env>.<base>`.
  const domain = `prev-${runId}.${baseDomain}`;
  const envA = "pr-a";
  const envB = "pr-b";
  const domainA = `prev-${runId}-${envA}.${baseDomain}`;
  const domainB = `prev-${runId}-${envB}.${baseDomain}`;

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = await prepareEnvFixture({ project, service, domain });

  note(`run ${runId} · cluster ${cluster} · region ${region}`);
  note(`projected domains: ${domainA} · ${domainB}`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(
        out.warnings.length === 0,
        `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`,
      );
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create an isolated cluster", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
    });

    let eip = "";
    await step("provision the edge + app node pair (the edge gets the Elastic IP)", async () => {
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", appNode, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
      const show = await cli.json<NodeShow>(["node", "show", edgeNode, "--cluster", cluster]);
      assert(!!show.node.publicIp, "edge node has a public (Elastic) IP");
      eip = show.node.publicIp!;
      note(`edge Elastic IP: ${eip} (a wildcard *.${baseDomain} → this EIP would cover every env)`);
    });

    await step(`deploy --env ${envA} --ttl 1m converges and surfaces the projected domain's DNS target`, async () => {
      const out = await cli.json<DeployJson>(
        ["deploy", "--env", envA, "--ttl", "1m", "--cluster", cluster, "--yes", "--timeout", "600"],
        { cwd: dir },
      );
      assertEquals(out.converged, true, "the env converged");
      const target = (out.dns ?? []).find((t) => t.domain === domainA);
      assert(!!target && target.eip === eip, `deploy reported ${domainA} → A ${eip} (DNS stays user-managed)`);
    });

    await step(`deploy --env ${envB} (no TTL) converges`, async () => {
      const out = await cli.json<DeployJson>(
        ["deploy", "--env", envB, "--cluster", cluster, "--yes", "--timeout", "600"],
        { cwd: dir },
      );
      assertEquals(out.converged, true, "the second env converged");
      const target = (out.dns ?? []).find((t) => t.domain === domainB);
      assert(!!target && target.eip === eip, `deploy reported ${domainB} → A ${eip}`);
    });

    await step("destroy --list-envs enumerates both envs with their expiry metadata", async () => {
      const out = await cli.json<EnvListJson>(["destroy", "--list-envs", "--cluster", cluster], { cwd: dir });
      assertEquals(out.envs.length, 2, "two environments are listed");
      const a = out.envs.find((p) => p.env === envA);
      const b = out.envs.find((p) => p.env === envB);
      assert(!!a && a.expiresAt !== null, `${envA} carries its --ttl expiry (${a?.expiresAt})`);
      assert(!!b && b.expiresAt === null, `${envB} has no TTL (never expires)`);
      assert(!!a && a.domains.includes(domainA), `${envA} marker records its projected domain`);
    });

    await step("destroy --prune-expired refuses --json without an explicit --yes (cron safety)", async () => {
      const res = await cli.run(["destroy", "--prune-expired", "--cluster", cluster, "--json"], { allowFail: true });
      assert(res.exitCode !== 0, "--prune-expired --json without --yes exits non-zero");
    });

    await step(`wait for ${envA}'s 1m TTL to lapse`, async () => {
      for (let i = 0; i < 24; i += 1) {
        const out = await cli.json<EnvListJson>(["destroy", "--list-envs", "--cluster", cluster], { cwd: dir });
        const a = out.envs.find((p) => p.env === envA);
        if (a?.expired) {
          note(`${envA} reported expired (deadline ${a.expiresAt})`);
          return;
        }
        await sleep(10_000);
      }
      assert(false, `${envA} reported expired within the poll window`);
    });

    await step(`destroy --prune-expired --yes destroys ONLY the expired env (${envA})`, async () => {
      const out = await cli.json<PrunePassJson>(
        ["destroy", "--prune-expired", "--cluster", cluster, "--yes", "--timeout", "300"],
        { cwd: dir },
      );
      assertEquals(out.pruned.length, 1, "exactly one env was pruned");
      assertEquals(out.pruned[0]!.owner, `${project}-${envA}`, "the pruned footprint is the expired env");
      assert((out.failed ?? []).length === 0, "no env failed to prune");
      assertEquals(out.kept.join(","), `${project}-${envB}`, "the TTL-less env was kept");
    });

    await step("after prune: containers stopped, marker swept — survivor untouched", async () => {
      const show = await cli.json<NodeShow>(["node", "show", appNode, "--cluster", cluster]);
      const services = show.status?.services ?? [];
      assert(
        !services.some((s) => s.project === `${project}-${envA}` && s.runningReplicas > 0),
        `no ${project}-${envA} container is still running`,
      );
      assert(
        services.some((s) => s.project === `${project}-${envB}` && s.runningReplicas > 0),
        `${project}-${envB} is still running (prune never touches a live sibling env)`,
      );

      const list = await cli.json<EnvListJson>(["destroy", "--list-envs", "--cluster", cluster], { cwd: dir });
      assertEquals(list.envs.length, 1, "only the surviving env is listed");
      assertEquals(list.envs[0]!.env, envB, "the survivor is the TTL-less env");
    });

    await step(`destroy --env ${envB} tears the survivor down end-to-end`, async () => {
      const out = await cli.json<EnvDestroyJson>(
        ["destroy", "--env", envB, "--cluster", cluster, "--yes", "--timeout", "300"],
        { cwd: dir },
      );
      assertEquals(out.destroyed, true, "destroy --env succeeded");
      assertEquals(out.owner, `${project}-${envB}`, "it destroyed the right footprint");
    });

    await step("a final prune pass is a clean no-op", async () => {
      const out = await cli.json<PrunePassJson>(["destroy", "--prune-expired", "--cluster", cluster, "--yes"], { cwd: dir });
      assertEquals(out.pruned.length, 0, "nothing left to prune");
      assertEquals(out.kept.length, 0, "no environments remain");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
