/**
 * launch-pad real-AWS regression for `node destroy --evacuate` — auto-evacuating a
 * cluster-placed footprint off a node and tearing it down in one command, instead of the
 * manual `node evacuate` → wait → `node destroy` two-step.
 *
 * Minimal + agent-agnostic: two `both` nodes running one cluster-placed **worker**
 * (schedule = "even", no domain → no Caddy/cert/DNS, no secrets), like e2e:rebalance.
 * Node ids are chosen so de-a sorts before de-b (S3-lexicographic order is what
 * `schedule = "even"` round-robins over), making the 3-replica split deterministic: a:2, b:1.
 *
 * It proves four things with just two instances:
 *
 *   1. guard       — `node destroy de-b` (no --evacuate/--force) REFUSES to orphan the replica.
 *   2. evacuate    — `node destroy de-b --evacuate` moves the replica to de-a, WAITS for it to
 *                    come up (a:3), then destroys de-b — all in one command.
 *   3. converged   — because --evacuate waits, de-a already runs 3 replicas when the command
 *                    returns, and de-b's registry entry is gone.
 *   4. last-node   — `node destroy de-a --evacuate` REFUSES (draining the last app node has
 *                    nowhere to move the replica → still would orphan → needs --force).
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:destroy-evacuate   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface ClusterDestroyJson {
  destroyed: string[];
  warnings: string[];
}
interface NodeDestroyJson {
  destroyed: string | string[];
  evacuated?: { project: string; nodes: string[] };
}

async function retry<T>(fn: () => Promise<T>, opts: { tries: number; delayMs: number; until: (r: T) => boolean }): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Count of running replicas of `service` on `node`. */
async function runningCount(cli: Cli, node: string, cluster: string, service: string): Promise<number> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? []).filter((r) => r.state === "running" && r.containerId).length;
}

/** Wait until `node` reports exactly `count` running replicas of `service`. */
async function waitForCount(cli: Cli, node: string, cluster: string, service: string, count: number): Promise<number> {
  return retry(() => runningCount(cli, node, cluster, service), {
    tries: 24,
    delayMs: 10_000,
    until: (n) => n === count,
  });
}

/** A throwaway cluster-placed worker (omits node → scheduled by schedule = "even"). */
function prepareWorkerFixture(spec: { project: string; service: string; replicas: number }): string {
  const src = join(repoRoot, "examples", "both-node-web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-destroy-evac-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad destroy --evacuate e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
schedule = "even"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = ${spec.replicas}
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS destroy --evacuate e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:destroy-evacuate\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-devac-${runId}`;
  // de-a sorts before de-b — load-bearing for `schedule = "even"` (a:2, b:1 at replicas=3).
  const nodeA = "de-a";
  const nodeB = "de-b";
  const project = "devac";
  const service = "worker";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareWorkerFixture({ project, service, replicas: 3 });

  note(`run ${runId} · cluster ${cluster} · region ${region} · cluster-placed worker (schedule=even)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "destroy-evacuate e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster (cleanup)", async () => {
      const out = await cli.json<ClusterDestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
    }).catch(() => {});
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create cluster + two both nodes", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      // Create de-a first, then de-b — both are app-pool members.
      await cli.run(["node", "create", nodeA, "--role", "both", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", nodeB, "--role", "both", "--cluster", cluster, "--yes"]);
    });

    await step("deploy the cluster-placed worker at replicas = 3 (even → a:2, b:1)", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const a = await waitForCount(cli, nodeA, cluster, service, 2);
      const b = await waitForCount(cli, nodeB, cluster, service, 1);
      assertEquals(a, 2, "node-a runs 2 replicas after the even-spread deploy");
      assertEquals(b, 1, "node-b runs 1 replica after the even-spread deploy");
    });

    await softStep("plain `node destroy de-b` refuses to orphan the replica", async () => {
      const res = await cli.run(["node", "destroy", nodeB, "--cluster", cluster, "--yes"], {
        cwd: dir,
        allowFail: true,
      });
      assert(res.exitCode !== 0, `destroy without --evacuate/--force refused (exit ${res.exitCode})`);
      assert(/orphan/i.test(res.stderr), "the refusal explains the service would be orphaned");
      // de-b must still exist (the refusal tore nothing down).
      const b = await runningCount(cli, nodeB, cluster, service);
      assertEquals(b, 1, "node-b still runs its replica after the refusal");
    });

    await step("`node destroy de-b --evacuate` moves the replica to de-a, waits, then destroys de-b", async () => {
      const out = await cli.json<NodeDestroyJson>(
        ["node", "destroy", nodeB, "--cluster", cluster, "--evacuate", "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      const destroyed = Array.isArray(out.destroyed) ? out.destroyed : [out.destroyed];
      assert(destroyed.includes(nodeB), `destroy reported ${nodeB} destroyed (${JSON.stringify(out.destroyed)})`);
      assert(out.evacuated?.nodes.includes(nodeB) === true, "destroy reported it auto-evacuated node-b first");

      // --evacuate WAITS for convergence, so de-a already runs all 3 replicas now.
      const a = await waitForCount(cli, nodeA, cluster, service, 3);
      assertEquals(a, 3, "all 3 replicas run on node-a after the evacuating destroy");

      // de-b is fully gone — its registry entry no longer resolves.
      const show = await cli.run(["node", "show", nodeB, "--cluster", cluster], { allowFail: true });
      assert(show.exitCode !== 0, `node-b registry entry is gone after destroy (node show exit ${show.exitCode})`);
    });

    await softStep("`node destroy de-a --evacuate` refuses — can't drain the last app node", async () => {
      const res = await cli.run(
        ["node", "destroy", nodeA, "--cluster", cluster, "--evacuate", "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir, allowFail: true },
      );
      assert(res.exitCode !== 0, `destroying the last app node with --evacuate refused (exit ${res.exitCode})`);
      assert(/orphan/i.test(res.stderr), "the refusal still explains the service would be orphaned");
      // de-a must survive the refused destroy, still running all 3 replicas.
      const a = await runningCount(cli, nodeA, cluster, service);
      assertEquals(a, 3, "node-a survives the refused destroy with all 3 replicas");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}". Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    process.exitCode = ran ? (printSummary() ? 0 : 1) : 0;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
