/**
 * launch-pad real-AWS regression for `launch-pad dns setup` — the Route53 write
 * integration that points a service's domain at its fronting node's Elastic IP.
 *
 * Deliberately minimal and FAST: one `both` node (which gets an Elastic IP) and a
 * web service pinned to it — but NO deploy/build/cert. `dns setup` resolves the
 * fronting node from config, reads its EIP from the registry, and UPSERTs a DNS-only
 * A record; then `dns verify` must resolve the domain to that EIP. Re-running `dns
 * setup` must be a no-op ("already set"). This guards the command without the slow,
 * fragile Let's-Encrypt path the full lifecycle e2e (`run.ts`) needs.
 *
 * Requires a Route53 hosted zone that owns the test domain (same prerequisite as the
 * full e2e). Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:dns   (`--keep` skips teardown)
 */
import { randomBytes } from "node:crypto";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { makeCli } from "./cli";
import { makeDns } from "./dns";
import { assert, assertEquals, log, note, printSummary, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));

interface NodeShow {
  node: { nodeId: string; role: string; publicIp: string | null; state: string };
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}
interface DnsSetupJson {
  plan: Array<{ domain: string; service: string; zoneId: string; ip: string; current: string[]; unchanged: boolean }>;
  skipped: string[];
  willWrite: number;
}
interface DnsVerifyJson {
  domain: string;
  status: string;
  ok: boolean;
  ips: string[];
  expectedIp: string | null;
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** A config-only fixture: a web service pinned to `node`, no Dockerfile (we never build). */
function prepareDnsFixture(spec: { project: string; service: string; node: string; domain: string }): string {
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-dns-"));
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad dns e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
node = "${spec.node}"
domain = "${spec.domain}"
port = 3000
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256

[service.healthCheck]
path = "/healthz"
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS dns e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:dns\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const baseDomain = process.env.LAUNCHPAD_E2E_DOMAIN ?? "e2e-test.launch-pad.agentsystem.dev";
  const runId = randomBytes(3).toString("hex");
  // A unique label inside the same hosted zone as the full e2e — never collides.
  const domain = `dns-${runId}.${baseDomain}`;
  const cluster = `e2e-dns-${runId}`;
  const node = "dns-both";
  const project = "dns";
  const service = "web";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dns = makeDns(region);
  const dir = prepareDnsFixture({ project, service, node, domain });

  let eip = "";
  let zoneId = "";

  note(`run ${runId} · cluster ${cluster} · region ${region} · ${domain}`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  const teardown = async (): Promise<void> => {
    await step("remove the DNS record + destroy the cluster", async () => {
      if (zoneId && eip) {
        try {
          await dns.deleteA(zoneId, domain, eip);
          log("DNS record removed");
        } catch (error) {
          log(`DNS cleanup warning: ${(error as Error).message}`);
        }
      }
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create an isolated cluster", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
    });

    await step("provision a both node (gets an Elastic IP)", async () => {
      await cli.run(["node", "create", node, "--role", "both", "--cluster", cluster, "--yes"]);
      const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
      assertEquals(show.node.role, "both", "node role is `both`");
      assert(!!show.node.publicIp, "both node has a public (Elastic) IP");
      eip = show.node.publicIp!;
      note(`node Elastic IP: ${eip}`);
    });

    await step("dns setup writes a DNS-only A record at the node's Elastic IP", async () => {
      const out = await cli.json<DnsSetupJson>(
        ["dns", "setup", "--cluster", cluster, "--yes", "--wait"],
        { cwd: dir },
      );
      assertEquals(out.skipped.length, 0, `nothing was skipped${out.skipped.length ? `: ${out.skipped.join("; ")}` : ""}`);
      assertEquals(out.plan.length, 1, "exactly one web domain was planned");
      const item = out.plan[0]!;
      assertEquals(item.domain, domain, "the planned domain matches the service domain");
      assertEquals(item.ip, eip, "the A record targets the node's Elastic IP");
      zoneId = item.zoneId;
      assert(!!zoneId, "dns setup resolved the Route53 hosted zone");
      note(`hosted zone: ${zoneId}`);
    });

    await step("dns verify resolves the domain to the Elastic IP", async () => {
      // Route53 reported INSYNC; the local resolver may still need a beat for the new
      // (low-TTL) record to be answerable. Retry until `dns verify` reports ok.
      const out = await retry(
        () => cli.json<DnsVerifyJson>(["dns", "verify", domain, "--cluster", cluster], { cwd: dir }),
        { tries: 24, delayMs: 15_000, until: (r) => r.status === "ok" },
      );
      assertEquals(out.status, "ok", `dns verify is ok (resolved ${out.ips.join(", ") || "nothing"})`);
      assert(out.ips.includes(eip), `the domain resolves to the Elastic IP ${eip}`);
      assertEquals(out.expectedIp, eip, "verify computed the expected EIP from the registry (no --expect needed)");
    });

    await step("re-running dns setup is a no-op (record already correct)", async () => {
      const out = await cli.json<DnsSetupJson>(["dns", "setup", "--cluster", cluster, "--yes"], { cwd: dir });
      assertEquals(out.willWrite, 0, "no records need writing on the second run");
      assertEquals(out.plan.length, 1, "the domain is still planned");
      assert(out.plan[0]!.unchanged, "the record is reported as already set (idempotent)");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --yes`);
      note(`  (and remove the DNS record: ${domain} → ${eip})`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
