/**
 * launchpad real-AWS regression for ARM/T4G empty-cluster bootstrap — deploying a
 * cluster-auto-placed service to a brand-new cluster that has NO nodes yet.
 *
 * Auto-placement on a fresh named cluster has no app pool, so the first deploy must
 * bootstrap the minimum Graviton topology itself: the dedicated edge node ("edge-1",
 * Caddy only) plus one generated app node behind it, then build/deploy the worker as
 * linux/arm64. Worker-only (no domain/cert/DNS) so it's fast, but it DOES build +
 * deploy via `--remote-build` (no local Docker daemon required).
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:empty-cluster   (`--keep` skips teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, listAppNodeIds, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string; instanceType: string; architecture: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

async function runningIds(cli: Cli, node: string, cluster: string, service: string): Promise<string[]> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? [])
    .filter((r) => r.state === "running" && r.containerId)
    .map((r) => r.containerId as string)
    .sort();
}

/** An auto-placed worker (placement is always the scheduler's) so deploy must bootstrap. */
function prepareClusterWorkerFixture(spec: { project: string; service: string }): string {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-empty-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad empty-cluster e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS empty-cluster e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:empty-cluster\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-arm-${runId}`;
  const project = "empty";
  const service = "worker";
  const bootstrapEdge = "edge-1"; // deploy's empty-cluster bootstrap edge (Caddy only)

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareClusterWorkerFixture({ project, service });

  note(`run ${runId} · cluster ${cluster} · region ${region} · ARM/T4G auto-placed worker, NO node create`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "empty-cluster e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create an isolated cluster (with NO nodes)", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
    });

    await step("deploy refuses with --no-create on an empty cluster", async () => {
      // The bootstrap must be opt-out-able: --no-create should still error, not provision.
      const res = await cli.run(["deploy", "--cluster", cluster, "--yes", "--no-create"], {
        cwd: dir,
        allowFail: true,
      });
      assert(res.exitCode !== 0, `deploy --no-create was refused on the empty cluster (exit ${res.exitCode})`);
      assert(/no app nodes/i.test(res.stderr), "the refusal explains the cluster has no app nodes");
    });

    let appNode = "";
    await step("deploy auto-bootstraps a t4g edge + app node and runs the worker", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--remote-build", "--timeout", DEPLOY_TIMEOUT_S], {
        cwd: dir,
      });
      const edge = await cli.json<NodeShow>(["node", "show", bootstrapEdge, "--cluster", cluster]);
      assertEquals(edge.node.nodeId, bootstrapEdge, `deploy auto-created the cluster edge "${bootstrapEdge}"`);
      assertEquals(edge.node.role, "edge", "the bootstrap edge node has role `edge`");
      assertEquals(edge.node.instanceType, "t4g.nano", "the bootstrap edge uses the t4g.nano default");
      assertEquals(edge.node.architecture, "arm64", "the bootstrap edge is arm64");
      assert(edge.status !== null, "the edge agent published status");

      const appNodes = await listAppNodeIds(cli, cluster);
      assertEquals(appNodes.length, 1, "deploy auto-created exactly one bootstrap app node");
      appNode = appNodes[0] as string;
      const show = await cli.json<NodeShow>(["node", "show", appNode, "--cluster", cluster]);
      assertEquals(show.node.nodeId, appNode, `deploy auto-created bootstrap app node "${appNode}"`);
      assertEquals(show.node.role, "app", "the bootstrap app node has role `app`");
      assertEquals(show.node.instanceType, "t4g.micro", "the bootstrap app node uses the t4g.micro floor");
      assertEquals(show.node.architecture, "arm64", "the bootstrap app node is arm64");
      assert(show.status !== null, "the app agent published status");
      const ids = await retry(() => runningIds(cli, appNode, cluster, service), {
        tries: 18,
        delayMs: 10_000,
        until: (r) => r.length === 1,
      });
      assertEquals(ids.length, 1, "the auto-placed worker is running on the bootstrapped app node");
    });

    await step("a second deploy is idempotent — no new node, same placement", async () => {
      const before = await runningIds(cli, appNode, cluster, service);
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--remote-build", "--timeout", DEPLOY_TIMEOUT_S], {
        cwd: dir,
      });
      const after = await runningIds(cli, appNode, cluster, service);
      assertEquals(after.join(","), before.join(","), "container ids unchanged after a same-version re-deploy (no re-bootstrap)");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
