/**
 * launch-pad real-AWS regression for empty-cluster bootstrap — deploying a
 * cluster-auto-placed service to a brand-new cluster that has NO nodes yet.
 *
 * Before this, cluster auto-placement (omit `node`/`nodes`) required a pre-created app
 * pool, so the first deploy to a fresh named cluster errored "no app nodes". Now deploy
 * auto-provisions a single co-located node ("app-1") and places onto it — parity with the
 * default cluster's single-node auto-provision. Worker-only (no domain/cert/DNS) so it's
 * fast and agent-agnostic, but it DOES build + deploy (needs Docker).
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:empty-cluster   (`--keep` skips teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

async function runningIds(cli: Cli, node: string, cluster: string, service: string): Promise<string[]> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? [])
    .filter((r) => r.state === "running" && r.containerId)
    .map((r) => r.containerId as string)
    .sort();
}

/** A cluster-AUTO-PLACED worker (omit `node`; `schedule = "even"`) so deploy must bootstrap. */
function prepareClusterWorkerFixture(spec: { project: string; service: string }): string {
  const src = join(repoRoot, "examples", "both-node-web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-empty-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad empty-cluster e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
schedule = "even"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS empty-cluster e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:empty-cluster\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-empty-${runId}`;
  const project = "empty";
  const service = "worker";
  const bootstrapNode = "app-1"; // deploy's empty-cluster bootstrap name

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareClusterWorkerFixture({ project, service });

  note(`run ${runId} · cluster ${cluster} · region ${region} · cluster-placed worker, NO node create`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "empty-cluster e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create an isolated cluster (with NO nodes)", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
    });

    await step("deploy refuses with --no-create on an empty cluster", async () => {
      // The bootstrap must be opt-out-able: --no-create should still error, not provision.
      const res = await cli.run(["deploy", "--cluster", cluster, "--yes", "--no-create"], {
        cwd: dir,
        allowFail: true,
      });
      assert(res.exitCode !== 0, `deploy --no-create was refused on the empty cluster (exit ${res.exitCode})`);
      assert(/no app nodes/i.test(res.stderr), "the refusal explains the cluster has no app nodes");
    });

    await step("deploy auto-bootstraps the first node and runs the worker", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const show = await cli.json<NodeShow>(["node", "show", bootstrapNode, "--cluster", cluster]);
      assertEquals(show.node.nodeId, bootstrapNode, `deploy auto-created the bootstrap node "${bootstrapNode}"`);
      assertEquals(show.node.role, "both", "the bootstrap node is a co-located (both) node");
      const ids = await retry(() => runningIds(cli, bootstrapNode, cluster, service), {
        tries: 18,
        delayMs: 10_000,
        until: (r) => r.length === 1,
      });
      assertEquals(ids.length, 1, "the cluster-placed worker is running on the bootstrapped node");
    });

    await step("a second deploy is idempotent — no new node, same placement", async () => {
      const before = await runningIds(cli, bootstrapNode, cluster, service);
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const after = await runningIds(cli, bootstrapNode, cluster, service);
      assertEquals(after.join(","), before.join(","), "container ids unchanged after a same-version re-deploy (no re-bootstrap)");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
