import { copyFileSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { repoRoot } from "./cli";

const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];

export interface FixtureSpec {
  project: string;
  service: string;
  appNode: string;
  edgeNode: string;
  domain: string;
  port: number;
  replicas: number;
  cpu: number;
  memory: number;
}

export interface Fixture {
  /** Working directory holding the app + launch-pad.toml (deploy `cwd`). */
  dir: string;
  /** Rewrite the app's RELEASE marker, commit, and return the new short git SHA. */
  setRelease(marker: string): Promise<string>;
}

function renderToml(s: FixtureSpec): string {
  return `# Generated by the launch-pad e2e harness — do not edit.
project = "${s.project}"

[[service]]
name = "${s.service}"
node = "${s.appNode}"
edge = "${s.edgeNode}"
dockerfile = "Dockerfile"
context = "."
cpu = ${s.cpu}
memory = ${s.memory}
replicas = ${s.replicas}
domain = "${s.domain}"
port = ${s.port}
env = { NODE_ENV = "production" }

  [service.healthCheck]
  path = "/healthz"

  [service.rollout]
  maxSurge = 1
  drainTimeout = "20s"
  stopGrace = "30s"
`;
}

/**
 * Copy the canonical example app into a throwaway temp dir, write a generated
 * launch-pad.toml, and init an independent git repo. Each `setRelease` commits a
 * real source change so the CLI's content-addressed image tag (git short SHA)
 * differs per release — proving a new image is built and pulled, not an env flip.
 */
export async function prepareFixture(spec: FixtureSpec): Promise<Fixture> {
  const src = join(repoRoot, "examples", "both-node-web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-e2e-"));

  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }

  // The CloudWatch agent tails container log files from the END, so a service that
  // logs only once at boot (then goes quiet) can have that line missed. Real apps
  // log continuously — make the fixture log every request so the logs assertion
  // exercises the pipeline with traffic the harness generates after deploy.
  const serverPath = join(dir, "server.js");
  const server = readFileSync(serverPath, "utf8");
  const withReqLog = server.replace(
    'app.get("/", (_req, res) => {',
    'app.get("/", (_req, res) => {\n  console.log(`request ${RELEASE} ${hostname()}`);',
  );
  if (withReqLog === server) throw new Error("could not inject request logging into server.js");
  const withSecretRoute = withReqLog.replace(
    'app.get("/healthz", (_req, res) => {',
    'app.get("/secret", (_req, res) => {\n  res.type("text/plain").send(`secret:${process.env.LAUNCHPAD_E2E_SECRET ?? "missing"}\\n`);\n});\n\napp.get("/healthz", (_req, res) => {',
  );
  if (withSecretRoute === withReqLog) throw new Error("could not inject secret route into server.js");
  writeFileSync(serverPath, withSecretRoute, "utf8");

  writeFileSync(join(dir, "launch-pad.toml"), renderToml(spec), "utf8");

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "e2e fixture"], { cwd: dir });

  async function setRelease(marker: string): Promise<string> {
    const serverPath = join(dir, "server.js");
    const source = readFileSync(serverPath, "utf8");
    const next = source.replace(/const RELEASE = "[^"]*";/, `const RELEASE = "${marker}";`);
    if (next === source) {
      throw new Error("could not find the RELEASE marker to rewrite in server.js");
    }
    writeFileSync(serverPath, next, "utf8");
    await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
    await execa("git", [...GIT_ID, "commit", "-q", "-m", `release ${marker}`], { cwd: dir });
    const sha = await execa("git", ["rev-parse", "--short=12", "HEAD"], { cwd: dir });
    return sha.stdout.trim();
  }

  return { dir, setRelease };
}
