/**
 * launchpad real-AWS regression for deploy history (`launchpad history`) — every deploy
 * appends an append-only event (who / when / image / converged) under the footprint's
 * `events/` prefix in S3.
 *
 * Worker-only (no domain → no Caddy/cert/DNS, no secrets), fast and agent-agnostic.
 *
 * Scenario:
 *   deploy worker (v1) → deploy (v2) → `history --json` shows 2 events, newest-first, each with
 *   the right image + converged=true + a caller ARN.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:history   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { appendFileSync, copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, step } from "./report";

const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface DeployJson {
  converged: boolean;
  services: Array<{ service: string; image: string }>;
}
interface HistoryJson {
  project: string;
  events: Array<{
    at: string;
    by: string;
    kind: string;
    converged: boolean | null;
    services: Array<{ service: string; image: string; replicas: number }>;
  }>;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

function prepareFixture(project: string): string {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-history-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad history e2e — do not edit.
project = "${project}"

[[service]]
name = "worker"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

const imageOf = (d: DeployJson): string => {
  const svc = d.services.find((s) => s.service === "worker");
  assert(!!svc?.image, "deploy reported an image for worker");
  return svc!.image;
};

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS history e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:history\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-hist-${runId}`;
  const edgeNode = "hist-edge";
  const appNode = "hist-app";
  const project = "hist";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareFixture(project);

  note(`run ${runId} · cluster ${cluster} · region ${region} · worker-only (no DNS/cert/secret)`);

  const commit = async (msg: string): Promise<void> => {
    await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
    await execa("git", [...GIT_ID, "commit", "-q", "-m", msg], { cwd: dir });
  };
  await execa("git", ["init", "-q"], { cwd: dir });
  await commit("history e2e fixture (v1)");

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {});
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  let v1 = "";
  let v2 = "";
  try {
    await step("create cluster + provision the edge + app node pair", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", appNode, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
    });

    await step("deploy the worker (v1)", async () => {
      const out = await cli.json<DeployJson>(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      assert(out.converged, "v1 deploy converged");
      v1 = imageOf(out);
    });

    await step("change content + deploy (v2)", async () => {
      appendFileSync(join(dir, "server.js"), `\n// history e2e ${runId} v2\n`);
      await commit("change worker content (v2)");
      const out = await cli.json<DeployJson>(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      assert(out.converged, "v2 deploy converged");
      v2 = imageOf(out);
      assert(v2 !== v1, "v2 image differs from v1");
    });

    await step("history records both deploys, newest-first, with images + converged + who", async () => {
      const hist = await cli.json<HistoryJson>(["history", "--service", "worker", "--cluster", cluster], { cwd: dir });
      assertEquals(hist.events.length, 2, "two deploy events were recorded");

      const [latest, first] = hist.events;
      assertEquals(latest!.services.find((s) => s.service === "worker")?.image, v2, "newest event is the v2 deploy");
      assertEquals(first!.services.find((s) => s.service === "worker")?.image, v1, "oldest event is the v1 deploy");
      assert(latest!.converged === true && first!.converged === true, "both events recorded converged=true");
      assert(latest!.kind === "build" && first!.kind === "build", "both events recorded kind=build");
      assert(!!latest!.by && latest!.by.includes("arn:aws"), `event records the caller ARN (${latest!.by})`);
      assert(latest!.at > first!.at, "events are ordered newest-first");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    process.exitCode = ran ? (printSummary() ? 0 : 1) : 0;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
