/**
 * launch-pad real-AWS regression for the **operator IAM policy** generator
 * (`launch-pad setup iam-policy`). The strongest possible proof that the generated
 * least-privilege policy is *sufficient*: mint a fresh IAM user that has ONLY that
 * policy, then run a real provision → deploy → undeploy → destroy with its credentials.
 * If the policy is missing a permission, an AccessDenied fails the matching step.
 *
 * It also proves the policy is *not* over-broad (a couple of negative checks: actions
 * outside the policy, and the same action in another region, are denied) and that the
 * document is syntactically valid (IAM Access Analyzer `validate-policy`).
 *
 * Deliberately a single `both` node running one **worker** service (no domain → no
 * Caddy/cert/DNS, no secrets) so it's agent-agnostic and fast, exactly like e2e:scale.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:operator-iam   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}
interface DoctorJson {
  ok: boolean;
  checks: Array<{ name: string; status: "pass" | "warn" | "fail" | "skip"; detail: string }>;
}

async function retry<T>(fn: () => Promise<T>, opts: { tries: number; delayMs: number; until: (r: T) => boolean }): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Running container ids for one service on a node, sorted. */
async function runningIds(cli: Cli, node: string, cluster: string, service: string): Promise<string[]> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? [])
    .filter((r) => r.state === "running" && r.containerId)
    .map((r) => r.containerId as string)
    .sort();
}

async function waitForReplicas(cli: Cli, node: string, cluster: string, service: string, count: number): Promise<string[]> {
  return retry(() => runningIds(cli, node, cluster, service), {
    tries: 18,
    delayMs: 10_000,
    until: (ids) => ids.length === count,
  });
}

/** A throwaway worker app (the example app, deployed with no domain → no ingress). */
function prepareWorkerFixture(spec: { project: string; service: string; node: string }): string {
  const src = join(repoRoot, "examples", "both-node-web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-opiam-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad operator-iam e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
node = "${spec.node}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

/** Run the real `aws` CLI with the dev's (admin) credentials. */
async function adminAws(args: string[], region: string): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  const res = await execa("aws", args, {
    reject: false,
    env: { ...(process.env as Record<string, string>), AWS_REGION: region, AWS_DEFAULT_REGION: region },
  });
  return { exitCode: res.exitCode ?? 1, stdout: res.stdout ?? "", stderr: res.stderr ?? "" };
}

/**
 * Build an env that uses ONLY the scoped user's static keys — every AWS credential /
 * config source the parent shell might carry (profile, SSO, web-identity, container
 * creds, a non-default credentials file) is stripped, so the scoped CLI can't silently
 * fall back to the admin identity and pass the least-privilege assertions under admin
 * power. Long-term IAM keys have no session token, so we deliberately don't set one.
 */
function scopedEnv(creds: { keyId: string; secret: string }, region: string): Record<string, string> {
  const env: Record<string, string> = {};
  for (const [k, v] of Object.entries(process.env)) {
    if (k.startsWith("AWS_") || v === undefined) continue;
    env[k] = v;
  }
  env.AWS_ACCESS_KEY_ID = creds.keyId;
  env.AWS_SECRET_ACCESS_KEY = creds.secret;
  env.AWS_REGION = region;
  env.AWS_DEFAULT_REGION = region;
  return env;
}

/** Run `aws` with the SCOPED user's credentials only (admin profile/keys cleared). */
async function scopedAws(
  args: string[],
  creds: { keyId: string; secret: string },
  region: string,
): Promise<{ exitCode: number; stdout: string; stderr: string }> {
  const res = await execa("aws", args, { reject: false, env: scopedEnv(creds, region) });
  return { exitCode: res.exitCode ?? 1, stdout: res.stdout ?? "", stderr: res.stderr ?? "" };
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS operator-iam e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:operator-iam\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const otherRegion = region === "us-west-2" ? "us-east-1" : "us-west-2";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-opiam-${runId}`;
  const node = "opiam-both";
  const project = "opiam";
  const service = "worker";
  const userName = `launch-pad-e2e-op-${runId}`;
  const policyName = `launch-pad-e2e-op-${runId}`;

  // Resolve the account so the generated policy ARNs are scoped to it.
  const id = await adminAws(["sts", "get-caller-identity", "--query", "Account", "--output", "text"], region);
  assert(id.exitCode === 0 && /^\d{12}$/.test(id.stdout.trim()), "resolved the AWS account id with admin creds");
  const account = id.stdout.trim();
  const policyArn = `arn:aws:iam::${account}:policy/${policyName}`;

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-admin-"));
  const homeScoped = mkdtempSync(join(tmpdir(), "launch-pad-home-scoped-"));
  const adminCli = makeCli({ home, region });
  const dir = prepareWorkerFixture({ project, service, node });
  const policyFile = join(dir, "operator-policy.json");

  note(`run ${runId} · cluster ${cluster} · region ${region} · account ${account}`);
  note(`scoped IAM user ${userName} · managed policy ${policyName}`);
  note(`isolated admin HOME=${home} · scoped HOME=${homeScoped}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "operator-iam e2e fixture"], { cwd: dir });

  let creds: { keyId: string; secret: string } | null = null;
  let accessKeyId: string | null = null;

  const teardown = async (): Promise<void> => {
    // 1. Tear down the cluster's AWS resources (admin creds; reads nodes from S3).
    await step("destroy the cluster (cleanup)", async () => {
      const out = await adminCli.json<DestroyJson>(["cluster", "destroy", cluster, "--region", region, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
    }).catch(() => {});
    // 2. Delete the scoped IAM user + ALL its access keys + the managed policy (admin
    // creds). List the keys rather than trusting the captured id, so a key that AWS
    // created but we failed to parse can't block delete-user and leak live credentials.
    await step("delete the scoped IAM user + policy", async () => {
      const listed = await adminAws(["iam", "list-access-keys", "--user-name", userName, "--output", "json"], region);
      if (listed.exitCode === 0) {
        const keys = (JSON.parse(listed.stdout) as { AccessKeyMetadata: Array<{ AccessKeyId: string }> }).AccessKeyMetadata ?? [];
        for (const k of keys) {
          await adminAws(["iam", "delete-access-key", "--user-name", userName, "--access-key-id", k.AccessKeyId], region);
        }
      } else if (accessKeyId) {
        await adminAws(["iam", "delete-access-key", "--user-name", userName, "--access-key-id", accessKeyId], region);
      }
      await adminAws(["iam", "detach-user-policy", "--user-name", userName, "--policy-arn", policyArn], region);
      await adminAws(["iam", "delete-user", "--user-name", userName], region);
      await adminAws(["iam", "delete-policy", "--policy-arn", policyArn], region);
      note("scoped IAM user + managed policy deleted");
    }).catch(() => {});
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(homeScoped, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("generate the operator policy + validate it (IAM Access Analyzer)", async () => {
      const policy = await adminCli.run(["setup", "iam-policy", "--account", account, "--region", region, "--json"]);
      writeFileSync(policyFile, policy.stdout, "utf8");
      const v = await adminAws(
        ["accessanalyzer", "validate-policy", "--policy-type", "IDENTITY_POLICY", "--policy-document", `file://${policyFile}`, "--output", "json"],
        region,
      );
      assert(v.exitCode === 0, `validate-policy ran (exit ${v.exitCode})`);
      const findings = (JSON.parse(v.stdout) as { findings: Array<{ findingType: string; issueCode: string }> }).findings ?? [];
      const errors = findings.filter((f) => f.findingType === "ERROR");
      for (const f of findings) note(`  validate-policy ${f.findingType}: ${f.issueCode}`);
      assert(errors.length === 0, `policy has no ERROR-level findings (${findings.length} total finding(s))`);
    });

    await step("create a scoped IAM user with ONLY the operator policy", async () => {
      const created = await adminAws(
        ["iam", "create-policy", "--policy-name", policyName, "--policy-document", `file://${policyFile}`, "--output", "json"],
        region,
      );
      assert(created.exitCode === 0, `created managed policy ${policyName}`);
      assert((await adminAws(["iam", "create-user", "--user-name", userName], region)).exitCode === 0, `created user ${userName}`);
      assert(
        (await adminAws(["iam", "attach-user-policy", "--user-name", userName, "--policy-arn", policyArn], region)).exitCode === 0,
        "attached the operator policy to the user",
      );
      const key = await adminAws(["iam", "create-access-key", "--user-name", userName, "--output", "json"], region);
      assert(key.exitCode === 0, "created an access key for the user");
      const parsed = JSON.parse(key.stdout) as { AccessKey: { AccessKeyId: string; SecretAccessKey: string } };
      accessKeyId = parsed.AccessKey.AccessKeyId;
      creds = { keyId: parsed.AccessKey.AccessKeyId, secret: parsed.AccessKey.SecretAccessKey };
    });

    const scoped = creds as unknown as { keyId: string; secret: string };
    const scopedCli = makeCli({
      home: homeScoped,
      region,
      clearAwsEnv: true,
      env: { AWS_ACCESS_KEY_ID: scoped.keyId, AWS_SECRET_ACCESS_KEY: scoped.secret },
    });

    await step("scoped credentials propagate + `doctor` passes (read path is sufficient)", async () => {
      // New IAM keys are eventually consistent — wait until STS recognizes them.
      const idOk = await retry(() => scopedAws(["sts", "get-caller-identity"], scoped, region), {
        tries: 20,
        delayMs: 3000,
        until: (r) => r.exitCode === 0,
      });
      assert(idOk.exitCode === 0, "scoped access key is usable");
      const doctor = await scopedCli.json<DoctorJson>(["doctor", "--region", region]);
      const failed = doctor.checks.filter((c) => c.status === "fail");
      for (const f of failed) note(`  doctor FAIL: ${f.name} — ${f.detail}`);
      assert(failed.length === 0, `doctor reports no failing checks under the scoped policy (ok=${doctor.ok})`);
    });

    await softStep("the scoped policy is NOT over-broad (least-privilege negative checks)", async () => {
      // An action the policy never grants must be denied…
      const listUsers = await scopedAws(["iam", "list-users"], scoped, region);
      assert(listUsers.exitCode !== 0 && /AccessDenied|not authorized/i.test(listUsers.stderr), "iam:ListUsers is denied (not in policy)");
      // …and the same allowed action in a DIFFERENT region is denied by the region condition.
      const otherRegionDescribe = await scopedAws(["ec2", "describe-vpcs", "--region", otherRegion], scoped, region);
      assert(
        otherRegionDescribe.exitCode !== 0 && /UnauthorizedOperation|AccessDenied|not authorized/i.test(otherRegionDescribe.stderr),
        `ec2:DescribeVpcs in ${otherRegion} is denied by the aws:RequestedRegion condition`,
      );
    });

    await step("scoped user provisions a both node (IAM + EC2 + EIP + SG + bucket)", async () => {
      await scopedCli.run(["cluster", "create", cluster, "--region", region]);
      await scopedCli.run(["node", "create", node, "--role", "both", "--cluster", cluster, "--yes"]);
      const show = await scopedCli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
      assertEquals(show.node.role, "both", "node role is `both` (provisioned under the scoped policy)");
    });

    await step("scoped user deploys a worker (ECR push + desired state) + converges", async () => {
      await scopedCli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const ids = await waitForReplicas(scopedCli, node, cluster, service, 1);
      assertEquals(ids.length, 1, "worker converged to 1 running replica under the scoped policy");
    });

    await step("scoped user undeploys + destroys the node (teardown perms suffice)", async () => {
      await scopedCli.run(["undeploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      await scopedCli.run(["node", "destroy", node, "--cluster", cluster, "--yes"]);
      note("scoped user terminated the instance + released its EIP/SG/IAM");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" + IAM user "${userName}".`);
      note(`  Clean up: LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --region ${region} --yes`);
      note(`  aws iam delete-access-key --user-name ${userName} --access-key-id ${accessKeyId ?? "<id>"}`);
      note(`  aws iam detach-user-policy --user-name ${userName} --policy-arn ${policyArn}; aws iam delete-user --user-name ${userName}; aws iam delete-policy --policy-arn ${policyArn}`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    process.exitCode = ran ? (printSummary() ? 0 : 1) : 0;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
