/**
 * launch-pad real-AWS regression for `rebalance` + `node evacuate` — redistributing a
 * cluster-placed footprint across the live app pool without rebuilding.
 *
 * Minimal + agent-agnostic: two `both` nodes running one cluster-placed **worker**
 * (schedule = "even", no domain → no Caddy/cert/DNS, no secrets), so it works on the
 * rust or ts agent, like e2e:scale. It proves three things with just two instances:
 *
 *   1. evacuate     — `node evacuate <b>` drains the footprint OFF node-b onto node-a.
 *   2. spread-back  — a plain `rebalance` re-includes node-b and spreads back onto it.
 *   3. destroy-safe — after evacuating node-b, `node destroy` (which refuses to orphan
 *                     scheduled services) succeeds because nothing is scheduled there.
 *
 * Node ids are chosen so node-a sorts before node-b (S3-lexicographic order is what
 * `schedule = "even"` round-robins over), making the 3-replica split deterministic: a:2, b:1.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:rebalance   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(fn: () => Promise<T>, opts: { tries: number; delayMs: number; until: (r: T) => boolean }): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Count of running replicas of `service` on `node`. */
async function runningCount(cli: Cli, node: string, cluster: string, service: string): Promise<number> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? []).filter((r) => r.state === "running" && r.containerId).length;
}

/** Wait until `node` reports exactly `count` running replicas of `service`. */
async function waitForCount(cli: Cli, node: string, cluster: string, service: string, count: number): Promise<number> {
  return retry(() => runningCount(cli, node, cluster, service), {
    tries: 24,
    delayMs: 10_000,
    until: (n) => n === count,
  });
}

/** A throwaway cluster-placed worker (omits node → scheduled by schedule = "even"). */
function prepareWorkerFixture(spec: { project: string; service: string; replicas: number }): string {
  const src = join(repoRoot, "examples", "both-node-web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-rebal-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad rebalance e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
schedule = "even"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = ${spec.replicas}
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS rebalance e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:rebalance\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-rebal-${runId}`;
  // node-a sorts before node-b — load-bearing for `schedule = "even"` (a:2, b:1 at replicas=3).
  const nodeA = "reb-a";
  const nodeB = "reb-b";
  const project = "rebal";
  const service = "worker";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareWorkerFixture({ project, service, replicas: 3 });

  note(`run ${runId} · cluster ${cluster} · region ${region} · cluster-placed worker (schedule=even)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "rebalance e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster (cleanup)", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
    }).catch(() => {});
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create cluster + two both nodes", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      // Create node-a first, then node-b — both are app-pool members.
      await cli.run(["node", "create", nodeA, "--role", "both", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", nodeB, "--role", "both", "--cluster", cluster, "--yes"]);
    });

    await step("deploy the cluster-placed worker at replicas = 3 (even → a:2, b:1)", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const a = await waitForCount(cli, nodeA, cluster, service, 2);
      const b = await waitForCount(cli, nodeB, cluster, service, 1);
      assertEquals(a, 2, "node-a runs 2 replicas after the even-spread deploy");
      assertEquals(b, 1, "node-b runs 1 replica after the even-spread deploy");
    });

    await step("evacuate node-b → its replica moves to node-a (a:3, b:0)", async () => {
      // `node evacuate` == `rebalance --drain node-b`: replan over {node-a} only.
      const out = await cli.json<{ rebalanced: boolean; drained: string | null; vacatedNodes: string[] }>(
        ["node", "evacuate", nodeB, "--cluster", cluster, "--yes"],
        { cwd: dir },
      );
      assert(out.rebalanced === true, "evacuate reported a move");
      assert(out.vacatedNodes.includes(nodeB), "node-b is reported vacated");
      const a = await waitForCount(cli, nodeA, cluster, service, 3);
      const b = await waitForCount(cli, nodeB, cluster, service, 0);
      assertEquals(a, 3, "all 3 replicas consolidated onto node-a after evacuate");
      assertEquals(b, 0, "node-b is drained after evacuate");
    });

    await step("plain rebalance spreads back onto node-b (a:2, b:1)", async () => {
      const out = await cli.json<{ rebalanced: boolean }>(["rebalance", "--cluster", cluster, "--yes"], { cwd: dir });
      assert(out.rebalanced === true, "rebalance reported a move back onto node-b");
      const a = await waitForCount(cli, nodeA, cluster, service, 2);
      const b = await waitForCount(cli, nodeB, cluster, service, 1);
      assertEquals(a, 2, "node-a back to 2 replicas after spread");
      assertEquals(b, 1, "node-b back to 1 replica after spread");
    });

    await softStep("a second rebalance is a no-op (already balanced)", async () => {
      const out = await cli.json<{ rebalanced: boolean; reason?: string }>(["rebalance", "--cluster", cluster, "--yes"], { cwd: dir });
      assert(out.rebalanced === false && out.reason === "already-balanced", "idempotent rebalance reports already-balanced");
    });

    await step("evacuate node-b, then `node destroy` succeeds (nothing scheduled there)", async () => {
      await cli.run(["node", "evacuate", nodeB, "--cluster", cluster, "--yes"], { cwd: dir });
      await waitForCount(cli, nodeB, cluster, service, 0);
      // destroy refuses to orphan scheduled services — after evacuate, node-b has none.
      const res = await cli.run(["node", "destroy", nodeB, "--cluster", cluster, "--yes"], { allowFail: true });
      assert(res.exitCode === 0, `node destroy succeeded after evacuate (exit ${res.exitCode})`);
      const a = await waitForCount(cli, nodeA, cluster, service, 3);
      assertEquals(a, 3, "all 3 replicas run on node-a after destroying the evacuated node-b");
    });

    await softStep("a pinned service can't be evacuated (config-locked placement)", async () => {
      // No deploy needed: the pinned-on-drain refusal fires before any published-state
      // read. A fresh footprint with a cluster-placed worker AND a service pinned to
      // node-a; evacuating node-a must refuse because the pinned service can't move.
      const pinnedDir = mkdtempSync(join(tmpdir(), "launch-pad-rebal-pin-"));
      writeFileSync(
        join(pinnedDir, "launch-pad.toml"),
        `project = "${project}-pin"\n\n` +
          `[[service]]\nname = "floating"\nschedule = "even"\ndockerfile = "Dockerfile"\ncontext = "."\ncpu = 128\nmemory = 128\nreplicas = 2\n\n` +
          `[[service]]\nname = "pinned"\nnode = "${nodeA}"\ndockerfile = "Dockerfile"\ncontext = "."\ncpu = 128\nmemory = 128\nreplicas = 1\n`,
        "utf8",
      );
      const res = await cli.run(["node", "evacuate", nodeA, "--cluster", cluster, "--yes"], { cwd: pinnedDir, allowFail: true });
      assert(res.exitCode !== 0, `evacuate refused a node hosting a pinned service (exit ${res.exitCode})`);
      assert(/pinned/i.test(res.stderr), "the refusal explains the service is pinned");
      rmSync(pinnedDir, { recursive: true, force: true });
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}". Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    process.exitCode = ran ? (printSummary() ? 0 : 1) : 0;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
