/**
 * launchpad real-AWS regression for `rebalance` + `node evacuate` — redistributing an
 * auto-placed footprint across the live app pool without rebuilding.
 *
 * Minimal: one edge + two app nodes running one auto-placed **worker** (no domain →
 * no Caddy/cert/DNS, no secrets), like e2e:scale. It proves four things:
 *
 *   1. evacuate     — `node evacuate <b>` drains the footprint OFF node-b onto node-a.
 *   2. spread-back  — a plain `rebalance` re-includes node-b and spreads back onto it.
 *   3. volume-safe  — a volume-bearing service is sticky: evacuating its host node is
 *                     refused (the data lives on that node's disk).
 *   4. destroy-safe — after evacuating node-b, `node destroy` (which refuses to orphan
 *                     scheduled services) succeeds because nothing is scheduled there.
 *
 * App-node ids are chosen so node-a sorts before node-b (the scheduler's tie-break over
 * equal free headroom is deterministic), making the 3-replica split deterministic: a:2, b:1.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:rebalance   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(fn: () => Promise<T>, opts: { tries: number; delayMs: number; until: (r: T) => boolean }): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Count of running replicas of `service` on `node`. */
async function runningCount(cli: Cli, node: string, cluster: string, service: string): Promise<number> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? []).filter((r) => r.state === "running" && r.containerId).length;
}

/** Wait until `node` reports exactly `count` running replicas of `service`. */
async function waitForCount(cli: Cli, node: string, cluster: string, service: string, count: number): Promise<number> {
  return retry(() => runningCount(cli, node, cluster, service), {
    tries: 24,
    delayMs: 10_000,
    until: (n) => n === count,
  });
}

/** A throwaway auto-placed worker (placement is always the scheduler's). */
function prepareWorkerFixture(spec: { project: string; service: string; replicas: number }): string {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-rebal-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad rebalance e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = ${spec.replicas}
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS rebalance e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:rebalance\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-rebal-${runId}`;
  // node-a sorts before node-b — load-bearing for the scheduler's deterministic
  // tie-break over equal free headroom (a:2, b:1 at replicas=3).
  const edgeNode = "reb-edge";
  const nodeA = "reb-a";
  const nodeB = "reb-b";
  const project = "rebal";
  const service = "worker";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareWorkerFixture({ project, service, replicas: 3 });

  note(`run ${runId} · cluster ${cluster} · region ${region} · auto-placed worker (edge + 2 app nodes)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "rebalance e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster (cleanup)", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
    }).catch(() => {});
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create cluster + edge + two app nodes", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      // Create node-a first, then node-b — both are app-pool members behind the edge.
      await cli.run(["node", "create", nodeA, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", nodeB, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
    });

    await step("deploy the auto-placed worker at replicas = 3 (bin-pack → a:2, b:1)", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const a = await waitForCount(cli, nodeA, cluster, service, 2);
      const b = await waitForCount(cli, nodeB, cluster, service, 1);
      assertEquals(a, 2, "node-a runs 2 replicas after the spread deploy");
      assertEquals(b, 1, "node-b runs 1 replica after the spread deploy");
    });

    await step("evacuate node-b → its replica moves to node-a (a:3, b:0)", async () => {
      // `node evacuate` == `rebalance --drain node-b`: replan over {node-a} only.
      const out = await cli.json<{ rebalanced: boolean; drained: string | null; vacatedNodes: string[] }>(
        ["node", "evacuate", nodeB, "--cluster", cluster, "--yes"],
        { cwd: dir },
      );
      assert(out.rebalanced === true, "evacuate reported a move");
      assert(out.vacatedNodes.includes(nodeB), "node-b is reported vacated");
      const a = await waitForCount(cli, nodeA, cluster, service, 3);
      const b = await waitForCount(cli, nodeB, cluster, service, 0);
      assertEquals(a, 3, "all 3 replicas consolidated onto node-a after evacuate");
      assertEquals(b, 0, "node-b is drained after evacuate");
    });

    await step("plain rebalance spreads back onto node-b (a:2, b:1)", async () => {
      const out = await cli.json<{ rebalanced: boolean }>(["rebalance", "--cluster", cluster, "--yes"], { cwd: dir });
      assert(out.rebalanced === true, "rebalance reported a move back onto node-b");
      const a = await waitForCount(cli, nodeA, cluster, service, 2);
      const b = await waitForCount(cli, nodeB, cluster, service, 1);
      assertEquals(a, 2, "node-a back to 2 replicas after spread");
      assertEquals(b, 1, "node-b back to 1 replica after spread");
    });

    await softStep("a second rebalance is a no-op (already balanced)", async () => {
      const out = await cli.json<{ rebalanced: boolean; reason?: string }>(["rebalance", "--cluster", cluster, "--yes"], { cwd: dir });
      assert(out.rebalanced === false && out.reason === "already-balanced", "idempotent rebalance reports already-balanced");
    });

    await softStep("a volume-bearing service is sticky — its host node can't be evacuated", async () => {
      // Deploy a second footprint whose only service mounts a named volume. The
      // scheduler places it on ONE node and it is sticky there: evacuating that node
      // must be refused (an evacuation-blocked error naming the volume service).
      const volDir = mkdtempSync(join(tmpdir(), "launch-pad-rebal-vol-"));
      const src = join(repoRoot, "examples", "web-worker");
      for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
        copyFileSync(join(src, file), join(volDir, file));
      }
      writeFileSync(
        join(volDir, "launch-pad.toml"),
        `project = "${project}-vol"\n\n` +
          `[[service]]\nname = "ledger"\ndockerfile = "Dockerfile"\ncontext = "."\ncpu = 128\nmemory = 128\nreplicas = 1\n\n` +
          `  [[service.volumes]]\n  name = "data"\n  path = "/data"\n`,
        "utf8",
      );
      await execa("git", ["init", "-q"], { cwd: volDir });
      await execa("git", [...GIT_ID, "add", "-A"], { cwd: volDir });
      await execa("git", [...GIT_ID, "commit", "-q", "-m", "rebalance volume fixture"], { cwd: volDir });
      try {
        await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: volDir });
        // Find which app node the scheduler picked for the volume service.
        const counts = await Promise.all([
          runningCount(cli, nodeA, cluster, "ledger"),
          runningCount(cli, nodeB, cluster, "ledger"),
        ]);
        const host = counts[0] > 0 ? nodeA : nodeB;
        assert((counts[0] ?? 0) + (counts[1] ?? 0) === 1, `the volume service runs exactly once (on ${host})`);
        const res = await cli.run(["node", "evacuate", host, "--cluster", cluster, "--yes"], { cwd: volDir, allowFail: true });
        assert(res.exitCode !== 0, `evacuate refused the volume service's host node (exit ${res.exitCode})`);
        assert(/volume/i.test(res.stderr), "the refusal explains the service has a volume");
      } finally {
        // Remove the volume footprint so the destroy-safety step that follows isn't blocked.
        await cli.run(["destroy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: volDir, allowFail: true });
        rmSync(volDir, { recursive: true, force: true });
      }
    });

    await step("evacuate node-b, then `node destroy` succeeds (nothing scheduled there)", async () => {
      await cli.run(["node", "evacuate", nodeB, "--cluster", cluster, "--yes"], { cwd: dir });
      await waitForCount(cli, nodeB, cluster, service, 0);
      // destroy refuses to orphan scheduled services — after evacuate, node-b has none.
      const res = await cli.run(["node", "destroy", nodeB, "--cluster", cluster, "--yes"], { allowFail: true });
      assert(res.exitCode === 0, `node destroy succeeded after evacuate (exit ${res.exitCode})`);
      const a = await waitForCount(cli, nodeA, cluster, service, 3);
      assertEquals(a, 3, "all 3 replicas run on node-a after destroying the evacuated node-b");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}". Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    process.exitCode = ran ? (printSummary() ? 0 : 1) : 0;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
