/**
 * launchpad real-AWS regression for `deploy --remote-build` — building the image on
 * AWS CodeBuild instead of local docker (the slim-CI-runner path).
 *
 * Worker-only (no domain → no Caddy/cert/DNS, no secrets), so it's fast. The deploy
 * runs with `docker` SHIMMED TO FAIL on PATH, proving end-to-end that no local docker
 * daemon is touched.
 *
 * Scenario:
 *   deploy --remote-build (v1, docker shimmed)  → CodeBuild builds + pushes; converges
 *   deploy --remote-build again (unchanged)     → image already in ECR; no new build
 *   change content + deploy --remote-build (v2) → new immutable image; container rolls
 *   cluster destroy                             → CodeBuild project + role + state gone
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:remote-build   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { appendFileSync, chmodSync, copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { CloudWatchLogsClient, DescribeLogGroupsCommand } from "@aws-sdk/client-cloudwatch-logs";
import { BatchGetProjectsCommand, CodeBuildClient } from "@aws-sdk/client-codebuild";
import { GetRoleCommand, IAMClient } from "@aws-sdk/client-iam";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface DeployJson {
  converged: boolean;
  services: Array<{ service: string; image: string; ok: boolean }>;
}
interface NodeShow {
  status: {
    services: Array<{ service: string; image: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** The image + running container ids the node reports for one service. */
async function observe(cli: Cli, node: string, cluster: string, service: string): Promise<{ image: string | null; ids: string[] }> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  const ids = (svc?.replicas ?? [])
    .filter((r) => r.state === "running" && r.containerId)
    .map((r) => r.containerId as string)
    .sort();
  return { image: svc?.image ?? null, ids };
}

async function waitForImage(cli: Cli, node: string, cluster: string, service: string, image: string): Promise<string> {
  const r = await retry(() => observe(cli, node, cluster, service), {
    tries: 24,
    delayMs: 10_000,
    until: (o) => o.image === image && o.ids.length === 1,
  });
  assertEquals(r.image, image, `node reports ${service} running image ${image.split(":").pop()}`);
  return r.ids[0]!;
}

function prepareFixture(project: string): string {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-remote-build-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  // CodeBuild egresses through shared NAT IPs that Docker Hub 429s for anonymous
  // pulls. Pin the base image to AWS's mirror of the official library so the
  // regression test is deterministic (the buildspec's retry covers transient 429s
  // for users who keep docker.io bases).
  const dockerfile = readFileSync(join(dir, "Dockerfile"), "utf8");
  writeFileSync(
    join(dir, "Dockerfile"),
    dockerfile.replace(/^FROM node:/m, "FROM public.ecr.aws/docker/library/node:"),
    "utf8",
  );
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad remote-build e2e — do not edit.
project = "${project}"

[[service]]
name = "worker"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

/**
 * A PATH directory whose `docker` immediately fails — any attempt to use local
 * docker during `deploy --remote-build` makes the run loudly fail.
 */
function makeDockerShim(): string {
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-docker-shim-"));
  const shim = join(dir, "docker");
  writeFileSync(shim, '#!/bin/sh\necho "FATAL: local docker invoked during --remote-build" >&2\nexit 1\n', "utf8");
  chmodSync(shim, 0o755);
  return dir;
}

function imageOf(deploy: DeployJson, service: string): string {
  const svc = deploy.services.find((s) => s.service === service);
  assert(!!svc?.image, `deploy reported an image for ${service}`);
  return svc!.image;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS remote-build e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:remote-build\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-rb-${runId}`;
  const edgeNode = "rb-edge";
  const appNode = "rb-app";
  const project = "rb";
  const service = "worker";
  const codebuildProject = `launch-pad-build-${cluster}`;
  const codebuildRole = `launch-pad-codebuild-${cluster}`;

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const shimDir = makeDockerShim();
  // Every CLI invocation sees the failing docker shim FIRST on PATH — the remote
  // build path must never shell out to docker locally.
  const cli = makeCli({ home, region, env: { PATH: `${shimDir}:${process.env.PATH ?? ""}` } });
  const dir = prepareFixture(project);

  note(`run ${runId} · cluster ${cluster} · region ${region} · worker-only · docker shimmed to fail`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  const commit = async (msg: string): Promise<void> => {
    await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
    await execa("git", [...GIT_ID, "commit", "-q", "-m", msg], { cwd: dir });
  };
  await execa("git", ["init", "-q"], { cwd: dir });
  await commit("remote-build e2e fixture (v1)");

  const codebuild = new CodeBuildClient({ region });
  const iam = new IAMClient({ region });
  const logs = new CloudWatchLogsClient({ region });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {});
    await softStep("CodeBuild project + service role + log group are gone after destroy", async () => {
      const projects = await codebuild.send(new BatchGetProjectsCommand({ names: [codebuildProject] }));
      assert((projects.projects ?? []).length === 0, "CodeBuild project deleted");
      let roleGone = false;
      try {
        await iam.send(new GetRoleCommand({ RoleName: codebuildRole }));
      } catch {
        roleGone = true;
      }
      assert(roleGone, "CodeBuild service role deleted");
      const groups = await logs.send(
        new DescribeLogGroupsCommand({ logGroupNamePrefix: `/aws/codebuild/${codebuildProject}` }),
      );
      assert((groups.logGroups ?? []).length === 0, "CodeBuild log group deleted");
    }).catch(() => {});
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
      rmSync(shimDir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  let v1 = "";
  let idV1 = "";
  try {
    await step("create cluster + provision the edge + app node pair", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", appNode, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
    });

    await step("deploy --remote-build (v1) — CodeBuild builds, no local docker", async () => {
      const res = await cli.run(
        ["deploy", "--remote-build", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S, "--json"],
        { cwd: dir },
      );
      assert(!/FATAL: local docker invoked/.test(res.stderr + res.stdout), "the docker shim was never invoked");
      const out = JSON.parse(res.stdout) as DeployJson;
      assert(out.converged, "v1 remote-build deploy converged");
      v1 = imageOf(out, service);
      note(`v1 image: ${v1}`);
      idV1 = await waitForImage(cli, appNode, cluster, service, v1);
    });

    await step("the per-cluster CodeBuild project exists with privileged docker env", async () => {
      const res = await codebuild.send(new BatchGetProjectsCommand({ names: [codebuildProject] }));
      const p = res.projects?.[0];
      assert(!!p, `CodeBuild project ${codebuildProject} exists`);
      assertEquals(p?.environment?.privilegedMode, true, "privileged mode enabled (docker-in-build)");
      assertEquals(p?.source?.type, "NO_SOURCE", "project uses NO_SOURCE (context comes from S3)");
    });

    await softStep("re-deploy unchanged is an idempotent no-op (image already in ECR)", async () => {
      const res = await cli.run(
        ["deploy", "--remote-build", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      assert(/already in ECR — skipping build/.test(res.stderr), "unchanged deploy skipped the remote build");
      const after = await observe(cli, appNode, cluster, service);
      assertEquals(after.image, v1, "still on v1");
      assertEquals(after.ids.join(","), idV1, "no container churn on the repeat deploy");
    });

    await step("change content + deploy --remote-build (v2) — a new immutable image rolls", async () => {
      appendFileSync(join(dir, "server.js"), `\n// rev 2 — ${runId}\n`);
      await commit("change worker content (v2)");
      const out = await cli.json<DeployJson>(
        ["deploy", "--remote-build", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      assert(out.converged, "v2 remote-build deploy converged");
      const v2 = imageOf(out, service);
      assert(v2 !== v1, `v2 image differs from v1 (${v2.split(":").pop()} ≠ ${v1.split(":").pop()})`);
      const idV2 = await waitForImage(cli, appNode, cluster, service, v2);
      assert(idV2 !== idV1, "the container rolled to a new id on v2");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    process.exitCode = ran ? (printSummary() ? 0 : 1) : 0;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
