/**
 * launchpad real-AWS regression for `node resize --evacuate` — non-disruptive vertical
 * scale: drain the project's cluster-placed services off the node (wait for them to be
 * confirmed running elsewhere), resize the emptied instance, then rebalance back — all in
 * one command, instead of plain `node resize` which stops the instance under its services.
 *
 * Minimal: one edge + two app nodes running one auto-placed **worker**
 * (no domain → no Caddy/cert/DNS, no secrets), like e2e:destroy-evacuate. App-node ids
 * are chosen so rz-a sorts before rz-b (the scheduler's tie-break over equal free
 * headroom is deterministic), making the 3-replica split deterministic: a:2, b:1.
 *
 * It proves five things with just two instances:
 *
 *   1. dry-run     — `resize rz-b --evacuate --dry-run` reports the drain plan, changes nothing.
 *   2. evacuate    — `resize rz-b --instance-type t3.medium --evacuate` first moves the replica
 *                    to rz-a and WAITS (observed live: rz-a hits 3 running replicas while the
 *                    resize command is still in flight — the replica ran elsewhere BEFORE the
 *                    instance stopped).
 *   3. resized     — rz-b comes back as a t3.medium with the bigger registry capacity.
 *   4. rebalanced  — the spread is restored (a:2, b:1) by the time the command returns.
 *   5. paused      — `resize --evacuate` on a paused node REFUSES (nothing running to protect;
 *                    the rebalance-back would wait on a stopped agent).
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:resize-evacuate   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string; instanceType: string; totalMemory: number };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface ClusterDestroyJson {
  destroyed: string[];
  warnings: string[];
}
interface ResizeJson {
  resized: string;
  instanceType: string;
  totalCpu: number;
  totalMemory: number;
  evacuated?: boolean;
}
interface ResizeDryRunJson {
  dryRun: boolean;
  node: string;
  to: { instanceType: string };
  evacuate?: boolean;
}

async function retry<T>(fn: () => Promise<T>, opts: { tries: number; delayMs: number; until: (r: T) => boolean }): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Count of running replicas of `service` on `node`. */
async function runningCount(cli: Cli, node: string, cluster: string, service: string): Promise<number> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? []).filter((r) => r.state === "running" && r.containerId).length;
}

/** Wait until `node` reports exactly `count` running replicas of `service`. */
async function waitForCount(cli: Cli, node: string, cluster: string, service: string, count: number): Promise<number> {
  return retry(() => runningCount(cli, node, cluster, service), {
    tries: 24,
    delayMs: 10_000,
    until: (n) => n === count,
  });
}

/** A throwaway auto-placed worker (placement is always the scheduler's). */
function prepareWorkerFixture(spec: { project: string; service: string; replicas: number }): string {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-resize-evac-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad resize --evacuate e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = ${spec.replicas}
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS resize --evacuate e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:resize-evacuate\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-resz-${runId}`;
  // rz-a sorts before rz-b — load-bearing for the scheduler's deterministic tie-break
  // over equal free headroom (a:2, b:1 at replicas=3).
  const edgeNode = "rz-edge";
  const nodeA = "rz-a";
  const nodeB = "rz-b";
  const project = "resz";
  const service = "worker";
  const targetType = "t3.medium"; // nodes are created as the default t3.small

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareWorkerFixture({ project, service, replicas: 3 });

  note(`run ${runId} · cluster ${cluster} · region ${region} · auto-placed worker (edge + 2 app nodes)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "resize --evacuate e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster (cleanup)", async () => {
      const out = await cli.json<ClusterDestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
    }).catch(() => {});
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create cluster + edge + two app nodes", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", nodeA, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", nodeB, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
    });

    await step("deploy the auto-placed worker at replicas = 3 (bin-pack → a:2, b:1)", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const a = await waitForCount(cli, nodeA, cluster, service, 2);
      const b = await waitForCount(cli, nodeB, cluster, service, 1);
      assertEquals(a, 2, "node-a runs 2 replicas after the spread deploy");
      assertEquals(b, 1, "node-b runs 1 replica after the spread deploy");
    });

    await softStep("`resize rz-b --evacuate --dry-run` reports the drain plan and changes nothing", async () => {
      const out = await cli.json<ResizeDryRunJson>(
        ["node", "resize", nodeB, "--cluster", cluster, "--instance-type", targetType, "--evacuate", "--dry-run"],
        { cwd: dir },
      );
      assert(out.dryRun === true, "dry-run reported dryRun: true");
      assertEquals(out.to.instanceType, targetType, "dry-run shows the target instance type");
      assert(out.evacuate === true, "dry-run shows the node will be drained first");
      const b = await runningCount(cli, nodeB, cluster, service);
      assertEquals(b, 1, "node-b still runs its replica after the dry-run");
    });

    await step("`resize rz-b --evacuate` drains to rz-a, resizes, rebalances back — replica never homeless", async () => {
      // Run the resize and concurrently watch rz-a: the drained replica must be RUNNING
      // there while the command is still in flight (i.e. before/while rz-b is down).
      const resize = cli.json<ResizeJson>(
        [
          "node", "resize", nodeB,
          "--cluster", cluster,
          "--instance-type", targetType,
          "--evacuate", "--yes",
          "--timeout", DEPLOY_TIMEOUT_S,
        ],
        { cwd: dir },
      );
      let sawFullDrain = false;
      let done = false;
      // Both callbacks: a bare `.finally()` would create an unhandled rejection on failure
      // (killing the process before teardown); the error itself surfaces at `await resize`.
      resize.then(
        () => {
          done = true;
        },
        () => {
          done = true;
        },
      );
      while (!done && !sawFullDrain) {
        const a = await runningCount(cli, nodeA, cluster, service).catch(() => 0);
        if (a === 3) sawFullDrain = true;
        else await sleep(5_000);
      }
      const out = await resize;

      assert(sawFullDrain, "rz-a ran all 3 replicas mid-command — the replica moved BEFORE the instance stopped");
      assertEquals(out.resized, nodeB, "resize reported rz-b resized");
      assertEquals(out.instanceType, targetType, `resize reported the new type (${targetType})`);
      assert(out.evacuated === true, "resize reported it evacuated first");

      // The command waits for the rebalance-back, so the spread is already restored.
      const a = await waitForCount(cli, nodeA, cluster, service, 2);
      const b = await waitForCount(cli, nodeB, cluster, service, 1);
      assertEquals(a, 2, "node-a is back to 2 replicas after the rebalance-back");
      assertEquals(b, 1, "node-b runs its replica again on the resized instance");

      const show = await cli.json<NodeShow>(["node", "show", nodeB, "--cluster", cluster]);
      assertEquals(show.node.instanceType, targetType, "the registry records the new instance type");
      assert(show.node.totalMemory > 2048, `the registry capacity grew (${show.node.totalMemory} MB)`);
    });

    await softStep("`resize --evacuate` on a paused node refuses (nothing running to protect)", async () => {
      await cli.run(["node", "pause", nodeB, "--cluster", cluster], { cwd: dir });
      const res = await cli.run(
        ["node", "resize", nodeB, "--cluster", cluster, "--instance-type", "t3.small", "--evacuate", "--yes"],
        { cwd: dir, allowFail: true },
      );
      assert(res.exitCode !== 0, `resize --evacuate on a paused node refused (exit ${res.exitCode})`);
      assert(/paused/i.test(res.stderr), "the refusal explains the node is paused");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}". Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    process.exitCode = ran ? (printSummary() ? 0 : 1) : 0;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
