/**
 * launchpad real-AWS regression for `rollback` — redeploying a service's previous (or a
 * specific `--to`) immutable ECR tag, auto-picking the prior build by ECR push time.
 *
 * Worker-only (no domain → no Caddy/cert/DNS, no secrets), so it's fast.
 *
 * Scenario:
 *   deploy worker (v1)                       → capture image v1
 *   change content, deploy (v2)              → new image v2
 *   rollback --service worker                → auto-picks the PREVIOUS build (v1), no rebuild
 *   rollback --service worker --to <v2-tag>  → rolls forward to v2
 *
 * Determinism: BOTH builds embed the run id, so this run's v1 + v2 are the two newest tags in
 * the (account-wide, reused) ECR repo — `rollback`'s "previous-by-push-time" therefore lands on
 * v1 regardless of tags left by earlier runs.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:rollback   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { appendFileSync, copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface DeployJson {
  converged: boolean;
  services: Array<{ service: string; image: string; ok: boolean }>;
}
interface NodeShow {
  status: {
    services: Array<{ service: string; image: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

async function observe(cli: Cli, node: string, cluster: string, service: string): Promise<{ image: string | null; ids: string[] }> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  const ids = (svc?.replicas ?? [])
    .filter((r) => r.state === "running" && r.containerId)
    .map((r) => r.containerId as string)
    .sort();
  return { image: svc?.image ?? null, ids };
}

async function waitForImage(cli: Cli, node: string, cluster: string, service: string, image: string): Promise<string> {
  const r = await retry(() => observe(cli, node, cluster, service), {
    tries: 24,
    delayMs: 10_000,
    until: (o) => o.image === image && o.ids.length === 1,
  });
  assertEquals(r.image, image, `node reports ${service} running tag ${image.split(":").pop()}`);
  return r.ids[0]!;
}

function imageOf(deploy: DeployJson, service: string): string {
  const svc = deploy.services.find((s) => s.service === service);
  assert(!!svc?.image, `deploy reported an image for ${service}`);
  return svc!.image;
}

const tagOf = (image: string): string => image.split(":").pop()!;

function prepareFixture(project: string, runId: string): string {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-rollback-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  // Embed the run id so v1's content (and therefore its tag) is unique to this run.
  appendFileSync(join(dir, "server.js"), `\n// rollback e2e ${runId} v1\n`);
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad rollback e2e — do not edit.
project = "${project}"

[[service]]
name = "worker"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS rollback e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:rollback\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-rb-${runId}`;
  const edgeNode = "rb-edge";
  const appNode = "rb-app";
  const project = "rb";
  const service = "worker";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareFixture(project, runId);

  note(`run ${runId} · cluster ${cluster} · region ${region} · worker-only (no DNS/cert/secret)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  const commit = async (msg: string): Promise<void> => {
    await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
    await execa("git", [...GIT_ID, "commit", "-q", "-m", msg], { cwd: dir });
  };
  await execa("git", ["init", "-q"], { cwd: dir });
  await commit("rollback e2e fixture (v1)");

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {});
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  let v1 = "";
  let v2 = "";
  let idV2 = "";
  try {
    await step("create cluster + provision the edge + app node pair", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", appNode, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
    });

    await step("deploy the worker (v1) and capture its image", async () => {
      const out = await cli.json<DeployJson>(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      assert(out.converged, "v1 deploy converged");
      v1 = imageOf(out, service);
      note(`v1 image: ${v1}`);
      await waitForImage(cli, appNode, cluster, service, v1);
    });

    await step("change content + deploy (v2)", async () => {
      appendFileSync(join(dir, "server.js"), `\n// rollback e2e ${runId} v2\n`);
      await commit("change worker content (v2)");
      const out = await cli.json<DeployJson>(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      assert(out.converged, "v2 deploy converged");
      v2 = imageOf(out, service);
      assert(v2 !== v1, `v2 image differs from v1 (${tagOf(v2)} ≠ ${tagOf(v1)})`);
      idV2 = await waitForImage(cli, appNode, cluster, service, v2);
    });

    await step("rollback --service worker auto-picks the previous build (v1)", async () => {
      const res = await cli.run(
        ["rollback", "--service", service, "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      assert(!/building .* linux\/amd64/i.test(res.stderr), "no image was built (rollback redeploys an existing tag)");
      const idV1 = await waitForImage(cli, appNode, cluster, service, v1);
      assert(idV1 !== idV2, "the container rolled to a new id on rollback");
    });

    await softStep("rollback --to <v2-tag> rolls forward to v2", async () => {
      await cli.run(
        ["rollback", "--service", service, "--to", tagOf(v2), "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      await waitForImage(cli, appNode, cluster, service, v2);
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    process.exitCode = ran ? (printSummary() ? 0 : 1) : 0;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
