/**
 * launchpad real-AWS regression for post-deploy scaling — the `scale` and `config`
 * commands and the config-lock relief that lets `replicas`/`env` change after the
 * first deploy.
 *
 * Deliberately minimal and FAST: one edge + one app node running a single **worker**
 * service (no domain → no Caddy/cert/DNS, no secrets), free of the Let's-Encrypt / SSM
 * dependencies the full lifecycle e2e (`run.ts`) needs — so it's a reliable guard
 * against scaling regressions.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:scale   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launchpad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Running container ids for one service on a node, sorted (stable for comparison). */
async function runningIds(cli: Cli, node: string, cluster: string, service: string): Promise<string[]> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? [])
    .filter((r) => r.state === "running" && r.containerId)
    .map((r) => r.containerId as string)
    .sort();
}

/** Wait until the node reports exactly `count` running replicas for the service. */
async function waitForReplicas(cli: Cli, node: string, cluster: string, service: string, count: number): Promise<string[]> {
  return retry(() => runningIds(cli, node, cluster, service), {
    tries: 18,
    delayMs: 10_000,
    until: (ids) => ids.length === count,
  });
}

/** A throwaway worker app (the example app, deployed with no domain → no ingress). */
function prepareWorkerFixture(spec: { project: string; service: string }): string {
  const src = join(repoRoot, "examples", "web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-scale-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launchpad scale e2e — do not edit.
project = "${spec.project}"

[[service]]
name = "${spec.service}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    "utf8",
  );
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS scale e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:scale\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-scale-${runId}`;
  const edgeNode = "scale-edge";
  const appNode = "scale-app";
  const project = "scale";
  const service = "worker";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareWorkerFixture({ project, service });

  note(`run ${runId} · cluster ${cluster} · region ${region} · worker-only (no DNS/cert/secret)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  // A clean git repo so the CLI's content-addressed image tag is stable.
  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "scale e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create an isolated cluster", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
    });

    await step("provision the edge + app node pair", async () => {
      await cli.run(["node", "create", edgeNode, "--role", "edge", "--cluster", cluster, "--yes"]);
      await cli.run(["node", "create", appNode, "--role", "app", "--edge", edgeNode, "--cluster", cluster, "--yes"]);
      const show = await cli.json<NodeShow>(["node", "show", appNode, "--cluster", cluster]);
      assertEquals(show.node.role, "app", "app node role is `app`");
    });

    await step("deploy the worker at replicas = 1", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const ids = await waitForReplicas(cli, appNode, cluster, service, 1);
      assertEquals(ids.length, 1, "worker is running 1 replica after the first deploy");
    });

    await step("scale replicas 1 → 3 via the CLI (config lock must PERMIT it)", async () => {
      // This is the crux: before the relief, a replicas change aborted deploy. `scale`
      // edits launch-pad.toml then runs a --service deploy; the lock must now allow it.
      await cli.run(
        ["scale", "replicas", service, "3", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      const ids = await waitForReplicas(cli, appNode, cluster, service, 3);
      assertEquals(ids.length, 3, "agent converged to 3 running replicas after scale-up");
      const toml = readFileSync(join(dir, "launch-pad.toml"), "utf8");
      assert(/replicas\s*=\s*3\b/.test(toml), "launch-pad.toml was edited to replicas = 3");
    });

    await softStep("set a non-secret env var with `config set` and roll the worker", async () => {
      const before = await runningIds(cli, appNode, cluster, service);
      await cli.run(
        ["config", "set", service, "LOG_LEVEL=debug", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      // env is part of the container config stamp, so all replicas roll to new ids.
      const after = await retry(() => runningIds(cli, appNode, cluster, service), {
        tries: 18,
        delayMs: 10_000,
        until: (ids) => ids.length === 3 && ids.join(",") !== before.join(","),
      });
      assert(
        after.length === 3 && after.join(",") !== before.join(","),
        "config set rolled all 3 replicas to new container ids",
      );
      const toml = readFileSync(join(dir, "launch-pad.toml"), "utf8");
      assert(/LOG_LEVEL\s*=\s*"debug"/.test(toml), "launch-pad.toml carries the new env var");
    });

    await step("scale replicas 3 → 1 via the CLI", async () => {
      await cli.run(
        ["scale", "replicas", service, "1", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      const ids = await waitForReplicas(cli, appNode, cluster, service, 1);
      assertEquals(ids.length, 1, "agent converged back to 1 running replica after scale-down");
    });

    await softStep("node destroy refuses to orphan the scheduled worker (without --force)", async () => {
      // The worker is still scheduled on this node — destroying it would orphan the
      // container, so `node destroy` must refuse. (`cluster destroy` in teardown is the
      // intentional whole-cluster path and still cleans it up, IAM included.)
      const res = await cli.run(["node", "destroy", appNode, "--cluster", cluster, "--yes"], { allowFail: true });
      assert(res.exitCode !== 0, `node destroy was refused while a service is scheduled (exit ${res.exitCode})`);
      assert(/orphan/i.test(res.stderr), "the refusal explains the service would be orphaned");
      const show = await cli.json<NodeShow>(["node", "show", appNode, "--cluster", cluster]);
      assertEquals(show.node.nodeId, appNode, "the node was NOT destroyed (it still hosts the worker)");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launchpad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
