/**
 * launch-pad real-AWS regression for `undeploy` — removing a service (or a whole
 * footprint) the config lock otherwise freezes, and the lock relief that lets a
 * follow-up `deploy` of the trimmed launch-pad.toml succeed.
 *
 * Deliberately minimal and FAST: one `both` node running TWO **worker** services
 * (no domain → no Caddy/cert/DNS, no secrets). Agent-agnostic (rust or ts) and free
 * of the Let's-Encrypt / SSM dependencies the full lifecycle e2e (`run.ts`) needs.
 *
 * Scenario:
 *   deploy {worker-a, worker-b}            → both run
 *   undeploy --service worker-b            → worker-b drains, worker-a stays
 *   (drop worker-b from toml) deploy       → MUST pass the config lock (baseline trimmed)
 *   undeploy (whole footprint)             → worker-a drains, baseline cleared
 *   deploy worker-a again                  → fresh first deploy works (identity unlocked)
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:undeploy   (add `--keep` to skip teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, softStep, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];

interface NodeShow {
  node: { nodeId: string; role: string; state: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}
interface UndeployJson {
  undeployed: boolean;
  removedServices: string[];
  nodes: string[];
  baselineCleared: boolean;
  drained: boolean | null;
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Count of running replicas for one service on a node (0 when the service is absent). */
async function runningCount(cli: Cli, node: string, cluster: string, service: string): Promise<number> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? []).filter((r) => r.state === "running" && r.containerId).length;
}

/** Wait until the node reports exactly `count` running replicas for the service. */
async function waitForRunning(
  cli: Cli,
  node: string,
  cluster: string,
  service: string,
  count: number,
): Promise<number> {
  return retry(() => runningCount(cli, node, cluster, service), {
    tries: 18,
    delayMs: 10_000,
    until: (n) => n === count,
  });
}

/** A throwaway project with N worker services (the example app, no domain → no ingress). */
function writeToml(dir: string, project: string, node: string, services: string[]): void {
  const blocks = services
    .map(
      (s) => `
[[service]]
name = "${s}"
node = "${node}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }
`,
    )
    .join("");
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad undeploy e2e — do not edit.\nproject = "${project}"\n${blocks}`,
    "utf8",
  );
}

function prepareFixture(project: string, node: string): string {
  const src = join(repoRoot, "examples", "both-node-web-worker");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-undeploy-"));
  for (const file of ["Dockerfile", "package.json", "server.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeToml(dir, project, node, ["worker-a", "worker-b"]);
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS undeploy e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:undeploy\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-undeploy-${runId}`;
  const node = "undeploy-both";
  const project = "undeploy";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareFixture(project, node);

  note(`run ${runId} · cluster ${cluster} · region ${region} · 2 workers (no DNS/cert/secret)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  const commit = async (msg: string): Promise<void> => {
    await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
    await execa("git", [...GIT_ID, "commit", "-q", "-m", msg], { cwd: dir });
  };

  // A clean git repo so the CLI's content-addressed image tag is stable per content.
  await execa("git", ["init", "-q"], { cwd: dir });
  await commit("undeploy e2e fixture");

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(
        out.warnings.length === 0,
        `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`,
      );
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create an isolated cluster", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
    });

    await step("provision a both node", async () => {
      await cli.run(["node", "create", node, "--role", "both", "--cluster", cluster, "--yes"]);
      const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
      assertEquals(show.node.role, "both", "node role is `both`");
    });

    await step("deploy two workers (worker-a + worker-b)", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      assertEquals(await waitForRunning(cli, node, cluster, "worker-a", 1), 1, "worker-a is running");
      assertEquals(await waitForRunning(cli, node, cluster, "worker-b", 1), 1, "worker-b is running");
    });

    await step("undeploy --service worker-b (config lock would otherwise freeze removal)", async () => {
      const out = await cli.json<UndeployJson>(
        ["undeploy", "--service", "worker-b", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      assert(out.undeployed, "undeploy reported success");
      assertEquals(out.removedServices.join(","), "worker-b", "only worker-b was removed");
      assert(out.baselineCleared === false, "the baseline was trimmed (not cleared) for a single-service undeploy");
      assertEquals(await waitForRunning(cli, node, cluster, "worker-b", 0), 0, "worker-b drained to 0 replicas");
      assertEquals(await runningCount(cli, node, cluster, "worker-a"), 1, "worker-a is untouched");
    });

    await step("redeploy the trimmed toml (worker-a only) — the lock must now PERMIT it", async () => {
      // The crux: dropping a [[service]] block normally trips the config lock ('service
      // removed'). Because undeploy trimmed the baseline, this deploy passes instead.
      writeToml(dir, project, node, ["worker-a"]);
      await commit("drop worker-b after undeploy");
      const res = await cli.run(
        ["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir, allowFail: true },
      );
      assert(res.exitCode === 0, `deploy of the trimmed toml succeeded (exit ${res.exitCode})\n${res.stderr}`);
      // Match the actual lock ERROR, not the benign "config lock: comparing…" step line.
      assert(
        !/not allowed after the initial deploy|only cpu, memory, replicas/i.test(res.stderr),
        "no config-lock violation was raised",
      );
      assertEquals(await waitForRunning(cli, node, cluster, "worker-a", 1), 1, "worker-a still running after redeploy");
    });

    await step("undeploy the whole footprint", async () => {
      const out = await cli.json<UndeployJson>(
        ["undeploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      assert(out.undeployed, "undeploy reported success");
      assert(out.baselineCleared, "the config baseline was cleared for a whole-footprint undeploy");
      assertEquals(await waitForRunning(cli, node, cluster, "worker-a", 0), 0, "worker-a drained to 0 replicas");
      const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
      const running = (show.status?.services ?? []).flatMap((s) =>
        (s.replicas ?? []).filter((r) => r.state === "running"),
      );
      assertEquals(running.length, 0, "no footprint services remain running on the node");
    });

    await softStep("re-deploy worker-a as a fresh first deploy (baseline was cleared)", async () => {
      // Proves the whole-footprint undeploy unlocked identity again: a brand-new deploy
      // of the (now single-service) toml succeeds as if it had never deployed.
      const res = await cli.run(
        ["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir, allowFail: true },
      );
      assert(res.exitCode === 0, `fresh deploy after full undeploy succeeded (exit ${res.exitCode})\n${res.stderr}`);
      assertEquals(await waitForRunning(cli, node, cluster, "worker-a", 1), 1, "worker-a runs again after a fresh deploy");
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
