/**
 * launch-pad real-AWS regression for **persistent volumes** — a declared
 * `[[service.volumes]]` is mounted by the agent and its data SURVIVES a container
 * replacement (the whole point: SQLite, uploads, local caches don't reset on deploy).
 *
 * Worker-only (no domain → no Caddy/cert/DNS). Uses the TypeScript agent (`--agent ts`),
 * which is the runtime that mounts volumes today. The `examples/worker-with-volume`
 * fixture appends one line to a file on the mounted volume on every boot, so the line
 * count == the number of times the container has started — if the volume persisted.
 *
 * Scenario:
 *   deploy (pinned worker, volume at /data)   → boot.log has 1 line
 *   deploy --restart (replace the container)  → boot.log has 2 lines  ← PERSISTED
 *   edit the volume path, deploy --service     → config lock REFUSES (volumes are identity)
 *
 * The running tally is observed through `launch-pad logs` (CloudWatch): the worker
 * prints `boot count: N` continuously, so the highest N seen == how many times the
 * container has started against the SAME volume.
 *
 * Run with:  LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:volumes   (`--keep` skips teardown)
 */
import { randomBytes } from "node:crypto";
import { copyFileSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { execa } from "execa";
import { type Cli, makeCli, repoRoot } from "./cli";
import { assert, assertEquals, note, printSummary, step } from "./report";

const sleep = (ms: number): Promise<void> => new Promise((r) => setTimeout(r, ms));
const DEPLOY_TIMEOUT_S = "600";
const GIT_ID = ["-c", "user.email=e2e@launch-pad.test", "-c", "user.name=launch-pad e2e"];

interface NodeShow {
  node: { nodeId: string; instanceId: string | null; role: string; state: string; agentType: string };
  status: {
    services: Array<{ service: string; replicas?: Array<{ containerId: string | null; state: string }> }>;
  } | null;
}
interface DestroyJson {
  destroyed: string[];
  warnings: string[];
}

async function retry<T>(
  fn: () => Promise<T>,
  opts: { tries: number; delayMs: number; until: (r: T) => boolean },
): Promise<T> {
  let last = await fn();
  for (let i = 1; i < opts.tries && !opts.until(last); i += 1) {
    await sleep(opts.delayMs);
    last = await fn();
  }
  return last;
}

/** Running container ids for one service on a node, sorted. */
async function runningIds(cli: Cli, node: string, cluster: string, service: string): Promise<string[]> {
  const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
  const svc = (show.status?.services ?? []).find((s) => s.service === service);
  return (svc?.replicas ?? [])
    .filter((r) => r.state === "running" && r.containerId)
    .map((r) => r.containerId as string)
    .sort();
}

async function waitForRunning(
  cli: Cli,
  node: string,
  cluster: string,
  service: string,
  predicate: (ids: string[]) => boolean,
): Promise<string[]> {
  return retry(() => runningIds(cli, node, cluster, service), { tries: 18, delayMs: 10_000, until: predicate });
}

interface LogsJson {
  events: Array<{ message: string }>;
}

/**
 * The highest `boot count: N` the worker has logged to CloudWatch. == how many times
 * the container has started against the SAME persistent volume (1 if it never persisted).
 */
async function maxBootCount(cli: Cli, service: string, cluster: string, dir: string): Promise<number> {
  const out = await cli.json<LogsJson>(["logs", service, "--cluster", cluster, "--since", "30m", "--json"], { cwd: dir });
  let max = 0;
  for (const e of out.events) {
    const m = /boot count: (\d+)/.exec(e.message);
    if (m) max = Math.max(max, Number.parseInt(m[1]!, 10));
  }
  return max;
}

/** Poll `launch-pad logs` until the worker reports at least `want` boots (log delivery lags). */
async function waitForBootCount(cli: Cli, service: string, cluster: string, dir: string, want: number): Promise<number> {
  return retry(() => maxBootCount(cli, service, cluster, dir), {
    tries: 24,
    delayMs: 10_000,
    until: (n) => n >= want,
  });
}

function writeToml(dir: string, project: string, node: string, service: string, volumePath: string): void {
  writeFileSync(
    join(dir, "launch-pad.toml"),
    `# Generated by the launch-pad volumes e2e — do not edit.
project = "${project}"

[[service]]
name = "${service}"
node = "${node}"
dockerfile = "Dockerfile"
context = "."
cpu = 256
memory = 256
replicas = 1
env = { NODE_ENV = "production" }

  [[service.volumes]]
  name = "data"
  path = "${volumePath}"
`,
    "utf8",
  );
}

function prepareFixture(project: string, node: string, service: string): string {
  const src = join(repoRoot, "examples", "worker-with-volume");
  const dir = mkdtempSync(join(tmpdir(), "launch-pad-volumes-"));
  for (const file of ["Dockerfile", "package.json", "worker.js", ".dockerignore"]) {
    copyFileSync(join(src, file), join(dir, file));
  }
  writeToml(dir, project, node, service, "/data");
  return dir;
}

async function main(): Promise<boolean> {
  if (process.env.LAUNCHPAD_E2E !== "1") {
    process.stderr.write(
      "LAUNCHPAD_E2E is not set to 1 — skipping the live AWS persistent-volumes e2e.\n" +
        "Run it with: LAUNCHPAD_E2E=1 [AWS_PROFILE=…] pnpm e2e:volumes\n",
    );
    return false;
  }

  const keep = process.argv.includes("--keep") || process.env.LAUNCHPAD_E2E_KEEP === "1";
  const region = process.env.LAUNCHPAD_E2E_REGION ?? "us-east-1";
  const runId = randomBytes(3).toString("hex");
  const cluster = `e2e-vol-${runId}`;
  const node = "vol-both";
  const project = "vol";
  const service = "ledger";

  const home = mkdtempSync(join(tmpdir(), "launch-pad-home-"));
  const cli = makeCli({ home, region });
  const dir = prepareFixture(project, node, service);

  note(`run ${runId} · cluster ${cluster} · region ${region} · persistent volumes (worker, --agent ts)`);
  note(`isolated LAUNCHPAD_HOME=${home}`);

  await execa("git", ["init", "-q"], { cwd: dir });
  await execa("git", [...GIT_ID, "add", "-A"], { cwd: dir });
  await execa("git", [...GIT_ID, "commit", "-q", "-m", "volumes e2e fixture"], { cwd: dir });

  const teardown = async (): Promise<void> => {
    await step("destroy the cluster + clean up state", async () => {
      const out = await cli.json<DestroyJson>(["cluster", "destroy", cluster, "--yes"]);
      note(`destroyed nodes: ${out.destroyed.join(", ") || "(none)"}`);
      assert(out.warnings.length === 0, `cluster destroy completed without warnings${out.warnings.length ? `: ${out.warnings.join("; ")}` : ""}`);
    }).catch(() => {
      /* recorded as a failed step; keep cleaning up */
    });
    try {
      rmSync(home, { recursive: true, force: true });
      rmSync(dir, { recursive: true, force: true });
    } catch {
      /* best-effort */
    }
  };

  try {
    await step("create a cluster + provision a both node on the TypeScript agent", async () => {
      await cli.run(["cluster", "create", cluster, "--region", region]);
      await cli.run(["node", "create", node, "--role", "both", "--cluster", cluster, "--agent", "ts", "--yes"]);
      const show = await cli.json<NodeShow>(["node", "show", node, "--cluster", cluster]);
      assertEquals(show.node.agentType, "ts", "node runs the TypeScript agent (which mounts volumes)");
      assert(!!show.node.instanceId, "node has an EC2 instance id");
    });

    let firstId = "";
    await step("deploy the worker — its volume records the first boot", async () => {
      await cli.run(["deploy", "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S], { cwd: dir });
      const ids = await waitForRunning(cli, node, cluster, service, (i) => i.length === 1);
      assertEquals(ids.length, 1, "worker is running 1 replica");
      firstId = ids[0] ?? "";
      const count = await waitForBootCount(cli, service, cluster, dir, 1);
      assertEquals(count, 1, "worker reports boot count 1 after the first boot");
      note("first boot wrote 1 line to the volume");
    });

    await step("deploy --restart replaces the container; the volume data PERSISTS", async () => {
      await cli.run(
        ["deploy", "--restart", "--service", service, "--cluster", cluster, "--yes", "--timeout", DEPLOY_TIMEOUT_S],
        { cwd: dir },
      );
      // Wait until the running container id is a NEW one (the replacement).
      const ids = await waitForRunning(cli, node, cluster, service, (i) => i.length === 1 && i[0] !== firstId);
      assert(ids[0] !== firstId, `container was replaced (${firstId.slice(0, 12)} → ${ids[0]?.slice(0, 12)})`);
      // The replacement re-mounts the SAME volume → its boot count is 2, not a reset to 1.
      const count = await waitForBootCount(cli, service, cluster, dir, 2);
      assertEquals(count, 2, "worker reports boot count 2 — the same volume was re-mounted, data survived the replace");
      note("the replacement boot saw the prior data and counted 2");
    });

    await step("config lock REFUSES changing the volume path after the first deploy", async () => {
      writeToml(dir, project, node, service, "/var/data"); // identity change
      await execa("git", [...GIT_ID, "commit", "-aqm", "move volume path"], { cwd: dir });
      const res = await cli.run(["deploy", "--service", service, "--cluster", cluster, "--yes"], {
        cwd: dir,
        allowFail: true,
      });
      assert(res.exitCode !== 0, "deploy is rejected when the volume path changes");
      assert(
        /not allowed after the initial deploy|locked fields changed|only cpu, memory/.test(res.stderr + res.stdout),
        "the rejection is a config-lock violation",
      );
      writeToml(dir, project, node, service, "/data"); // restore so teardown is clean
    });
  } finally {
    if (keep) {
      note(`--keep set — leaving cluster "${cluster}" running. Tear it down later with:`);
      note(`  LAUNCHPAD_HOME=${home} launch-pad cluster destroy ${cluster} --yes`);
    } else {
      await teardown();
    }
  }

  return true;
}

main()
  .then((ran) => {
    if (!ran) {
      process.exitCode = 0;
      return;
    }
    process.exitCode = printSummary() ? 0 : 1;
  })
  .catch((error) => {
    process.stderr.write(`\n${error?.stack ?? String(error)}\n`);
    process.exitCode = printSummary() ? 1 : 1;
  });
